/* textual representation of constants found in the scripts */

/*	names_for_the_"PERSON"_command
	note_that_all_typos_and/or_inconsistencies_are_transcribed_as-is_from_the_US_releases
	TODO:_fix_these_names, maybe_add_localization? */

/* zeroes are required because apollo introduces 5 additional slots */
char *speakers[4][60] = {
	{ /* names from phoenix 1 */
	"SPEAKER_EMPTY_00",		"SPEAKER_UNK_01",	"SPEAKER_PHOENIX_02",	"SPEAKER_POLICE",	"SPEAKER_MAYA",
	"SPEAKER_MIA_05",		"SPEAKER_ALARMCLOCK",	"SPEAKER_MIA_07",	"SPEAKER_JUDGE",	"SPEAKER_EDGEWORTH_09",
	"SPEAKER_PAYNE",		"SPEAKER_INTERPHONE",	"SPEAKER_GROSSBERG",	"SPEAKER_CELLULAR",	"SPEAKER_PUBLIC",
	"SPEAKER_UNK_15",		"SPEAKER_PENNY",	"SPEAKER_OLDBAG",	"SPEAKER_MANELLA",	"SPEAKER_TV",
	"SPEAKER_GUMSHOE",		"SPEAKER_WHITE",	"SPEAKER_APRIL",	"SPEAKER_BELLBOY",	"SPEAKER_VASQUEZ",
	"SPEAKER_BUTZ_25",		"SPEAKER_SAHWIT",	"SPEAKER_WILL",		"SPEAKER_CODY",		"SPEAKER_PHOENIX_29",
	"SPEAKER_EDGEWORTH_30",		"SPEAKER_LOTTA",	"SPEAKER_YOGI",		"SPEAKER_KARMA",	"SPEAKER_PARROT",
	"SPEAKER_MISSILE",		"SPEAKER_UNCLE",	"SPEAKER_GUARD_37",	"SPEAKER_TEACHER",	"SPEAKER_EDGEWORTH_39",
	"SPEAKER_BUTZ_40",		"SPEAKER_EMPTY_41",	"SPEAKER_EMPTY_42",	"SPEAKER_CHIEF",	"SPEAKER_EMA",
	"SPEAKER_LANA",			"SPEAKER_MARSHALL",	"SPEAKER_MEEKINS",	"SPEAKER_GOODMAN",	"SPEAKER_GANT",
	"SPEAKER_ANGEL",		"SPEAKER_GUARD_51",	"SPEAKER_OFFICER",	"SPEAKER_PATROLMAN",	"SPEAKER_EMPTY_54",
	0, 0, 0, 0, 0
	},
	{ /* names from phoenix 2 */
	"SPEAKER_EMPTY_00",		"SPEAKER_UNK_01",	"SPEAKER_UNK_02",		"SPEAKER_PHOENIX",		"SPEAKER_MAYA",
	"SPEAKER_MIA_05",		"SPEAKER_MIA_06",	"SPEAKER_JUDGE",		"SPEAKER_EDGEWORTH",		"SPEAKER_PAYNE",
	"SPEAKER_GUMSHOE",		"SPEAKER_PHONE",	"SPEAKER_PUBLIC",		"SPEAKER_BAILIFF",		"SPEAKER_VON_KARMA_14",
	"SPEAKER_VON_KARMA_15",		"SPEAKER_WELLINGTON",	"SPEAKER_BYRDE_17",		"SPEAKER_BYRDE_18",		"SPEAKER_INI",
	"SPEAKER_PEARL",		"SPEAKER_MORGAN",	"SPEAKER_HOTTI",		"SPEAKER_GREY",			"SPEAKER_LOTTA",
	"SPEAKER_MIA_25",		"SPEAKER_NURSE",	"SPEAKER_MIMI",			"SPEAKER_REGINA",		"SPEAKER_MAX",
	"SPEAKER_BEN",			"SPEAKER_MOE",		"SPEAKER_ACRO",			"SPEAKER_TRILO",		"SPEAKER_MONEY",
	"SPEAKER_ENGARDE",		"SPEAKER_ANDREWS",	"SPEAKER_DE_KILLER_37",		"SPEAKER_DE_KILLER_38",		"SPEAKER_OLDBAG",
	"SPEAKER_POWERS",		"SPEAKER_TV",		"SPEAKER_EMPTY_42",		"SPEAKER_EMPTY_43",		"SPEAKER_EMPTY_44",
	"SPEAKER_CELESTE",		"SPEAKER_RUSSELL",	"SPEAKER_BELLBOY",		"SPEAKER_PA_NOTICE",		"SPEAKER_RAY_GUN",
	"SPEAKER_CHIEF",		"SPEAKER_DETECTIVE",	"SPEAKER_JAILER",		"SPEAKER_SHOE",			"SPEAKER_DOE",
	0, 0, 0, 0, 0
	},
	{ /* names from phoenix 3 */
	"SPEAKER_PHOENIX",	"SPEAKER_MIA",		"SPEAKER_GROSSBERG",	"SPEAKER_PAYNE",	"SPEAKER_JUDGE",
	"SPEAKER_DAHLIA",	"SPEAKER_UNK",		"SPEAKER_SWALLOW",	"SPEAKER_JUDGE",	"SPEAKER_RON",
	"SPEAKER_DESIRÉE",	"SPEAKER_DEMASQUE",	"SPEAKER_ANDREWS",	"SPEAKER_GODOT",	"SPEAKER_ATMEY",
	"SPEAKER_PEARL",	"SPEAKER_ANNOUNCER",	"SPEAKER_PHONE",	"SPEAKER_GUMSHOE",	"SPEAKER_BUTZ",
	"SPEAKER_MAYA",		"SPEAKER_BAILIFF",	"SPEAKER_OFFICER",	"SPEAKER_BUZZER",	"SPEAKER_ARMSTRONG",
	"SPEAKER_BASIL",	"SPEAKER_VIOLA",	"SPEAKER_TIGRE",	"SPEAKER_BYRDE",	"SPEAKER_KUDO",
	"SPEAKER_CHIEF",	"SPEAKER_OLD_MAN",	"SPEAKER_DETECTIVE",	"SPEAKER_THE_TIGER",	"SPEAKER_PROGRAMMER",
	"SPEAKER_VALERIE",	"SPEAKER_FAWLES",	"SPEAKER_EDGEWORTH",	"SPEAKER_MELISSA",	"SPEAKER_ARMANDO",
	"SPEAKER_BIKINI",	"SPEAKER_IRIS",		"SPEAKER_LAURISE",	"SPEAKER_ELISE",	"SPEAKER_VON_KARMA",
	"SPEAKER_MORGAN",	"SPEAKER_MISTY",	"SPEAKER_OLDBAG",	"SPEAKER_RAY_GUN",	"SPEAKER_BLANK_49",
	"SPEAKER_VIOLETTA",	"SPEAKER_BLANK_51",	"SPEAKER_BLANK_52",	"SPEAKER_BLANK_53",	"SPEAKER_BLANK_54",
	0, 0, 0, 0, 0
	},
	{ /* names from apollo */
	"SPEAKER_EMPTY_00",		"SPEAKER_EMPTY_01",		"SPEAKER_UNK_02",		"SPEAKER_UNK_03",		"SPEAKER_APOLLO",
	"SPEAKER_TRUCY_05",		"SPEAKER_KRISTOPH_06",		"SPEAKER_PHOENIX",		"SPEAKER_KRISTOPH_08",		"SPEAKER_EMA",
	"SPEAKER_JUDGE",		"SPEAKER_PAYNE",		"SPEAKER_OLGA",			"SPEAKER_ALITA",		"SPEAKER_WOCKY",
	"SPEAKER_GUY",			"SPEAKER_PLUM",			"SPEAKER_BIG_WINS",		"SPEAKER_HICKFIELD",		"SPEAKER_VERA_19",
	"SPEAKER_BRUSHEL",		"SPEAKER_PHOENIX",		"SPEAKER_GUMSHOE",		"SPEAKER_KRISTOPH_23",		"SPEAKER_KRISTOPH_24",
	"SPEAKER_VALANT",		"SPEAKER_DREW",			"SPEAKER_TRUCY_27",		"SPEAKER_VERA_28",		"SPEAKER_MEEKINS",
	"SPEAKER_STICKLER",		"SPEAKER_ZAK",			"SPEAKER_SMITH",		"SPEAKER_VALANT",		"SPEAKER_LAMIROIR",
	"SPEAKER_MACHI",		"SPEAKER_LE_TOUSE",		"SPEAKER_DARYAN",		"SPEAKER_PLACEHOLDER_38",	"SPEAKER_PLACEHOLDER_39",
	"SPEAKER_PLACEHOLDER_40",	"SPEAKER_PLACEHOLDER_41",	"SPEAKER_PLACEHOLDER_42",	"SPEAKER_BAILIFF",		"SPEAKER_OFFICER",
	"SPEAKER_ANNOUNCER",		"SPEAKER_MR._HAT",		"SPEAKER_MERAKTIS",		"SPEAKER_ENIGMAR",		"SPEAKER_PUBLIC",
	"SPEAKER_MAGNIFI",		"SPEAKER_NO._6",		"SPEAKER_GUARD",		"SPEAKER_KLAVIER",		"SPEAKER_THALASSA",
	"SPEAKER_STAFF",		"SPEAKER_OLD_LADY",		"SPEAKER_KRISTOPH_57",		"SPEAKER_TV",			"SPEAKER_BLANK_59"
	}
	
};

char *personplacement[4] = {
	"PLACE_DEFAULT", "PLACE_RIGHT", "PLACE_LEFT", "PLACE_UNK"
};

char *colors[4] = {
	"COLOR_WHITE", "COLOR_RED", "COLOR_BLUE", "COLOR_GREEN"
};

char *shiftdirection[4] = {
	"SHIFT_LEFT", "SHIFT_RIGHT", "SHIFT_UP", "SHIFT_DOWN"
};

char *bgshift[2] = {
	"BG_NOSHIFT", "BG_SHIFT"
};

char *cmd35flaghint[2] = {
	"SKIP_IF_FLAG_SET", "SKIP_IF_FLAG_UNSET"
};

char *cmd35jumphint[2] = {
	"JUMP_THIS_SECTION", "JUMP_OTHER_SECTION"
};

/* multilang backgrounds share their number! */
/* TODO: add support for multiple games */
/* 4096 is the size per game due to BGSPC, this may change due to various weird leftover commands though */
char *backgrounds[4][4096] = {
	{
		/* phoenix 1 */
		"BG000_MIAS_OFFICE_NIGHT",
		"BG001_MIAS_OFFICE_DAY",
		"BG002_DEFENDANT_LOBBY",
		"BG003_COURT_DEFENSE",
		"BG004_COURT_PROSECUTION",
		"BG005_COURT_STAND",
		"BG006_COURT_FULL",
		"BG007_COURT_DEFENSE_PARTNER",
		"BG008_COURT_JUDGE",
		"BG009_MIAS_OFFICE_ENTRANCE",
		"BG010_DEAD_MIA_WITH_MAYA",
		"BG011_GLOBAL_STUDIOS_PATH", 
		"BG012_STAFF_AREA",
		"BG013_MIA_DODGING_RIGHT",
		"BG014_MIA_DODGING_LEFT",
		"BG015_MAP_OF_MIAS_OFFICE",
		"BG016_APRIL_AND_BELLBOY",
		"BG017_MIAS_OFFICE_BODY",
		"BG018_PHOENIX_WITH_MAYA_AND_MIA",
		"BG019_STUDIO_2_INSIDE",
		"BG020_APRIL_ON_PHONE",
		"BG021_REDD_ATTACKING", 
		"BG022_MIA_BEING_ATTACKED",
		"BG023_THINKER_AS_WEAPON",
		"BG024_DRESSING_ROOM", 
		"BG025_GLOBAL_STUDIOS_MAIN_GATE", 
		"BG026_STUDIO_1",
		"BG027_GAVEL_SLAM_2",
		"BG028_GAVEL_SLAM_3",
		"BG029_MAP_OF_MIAS_OFFICE_WITH_FOV",
		"BG030_DETENTION_CENTER",
		"BG031_BLUECORP_CEO_OFFICE",
		"BG032_GATEWATER_APRILS_ROOM",
		"BG033_THINKER_WITH_BLOOD",
		"BG034_CINDY_DEAD_ON_FLOOR",
		"BG035_SAHWIT_AFTER_MURDER",
		"BG036_SAHWIT_CLUELESS",
		"BG037_SAHWIT_THINKING",
		"BG038_SAHWIT_HAVING_IDEA",
		"BG039_GROSSBERGS_OFFICE",
		"BG040_GROSSBERGS_OFFICE_NO_PAINTING",
		"BG041_SAHWIT_CAUGHT",
		"BG042_SAHWIT_SEEING_LARRY",
		"BG043_SAHWIT_FINDING_CINDY",
		"BG044_STUDIO_2_ENTRANCE", 
		0, 0, 
		"BG047_GAVEL_SLAM_1",
		0, 
		"BG049_STEEL_SAMURAI_BROKEN_LEG",
		"BG050_FINDING_DEAD_HAMMER",
		"BG051_HAMMER_STEALING_COSTUME",
		"BG052_VASQUEZ_AFTER_MURDER", 
		"BG053_STAFF_AT_LUNCH", 
		"BG054_HAMMER_AND_VASQUEZ_AT_STUDIO_2", 
		"BG055_CODY_SEES_SAMURAI",
		"BG056_PHOTO_OF_SAMURAI_AT_STUDIO_2", 
		"BG057_INCIDENT_AT_STUDIO_2_5_YEARS_AGO", 
		"BG058_STUDIO_2_INSIDE_WITH_MIB", 
		"BG059_PINK_PRINCESS_POSTER", 
		"BG060_MONKEY_HEAD_ON_STUDIO_PATH",
		"BG061_MAP_OF_GLOBAL_STUDIOS", 
		"BG062_ACTORS_TRAINING", 
		"BG063_STEEL_SAMURAI_POSTER", 
		0, 0,
		"BG066_CLOSEUP_SPEEDLINES",
		0, 0,
		"BG069_STEEL_SAMURAI_MOON",
		"BG070_GOURD_LAKE_ENTRANCE",
		"BG071_GOURD_LAKE_PARK_DECORATED",
		"BG072_GOURD_LAKE_PARK",
		"BG073_GOURD_LAKE_FOREST",
		"BG074_STEEL_SAMURAI_MOON_GRASS",
		0, 
		"BG076_STEEL_SAMURAI_IN_ACTION",
		"BG077_GOURD_LAKE_BOAT_RENTAL",
		"BG078_GOURD_LAKE_BOAT_RENTAL_INSIDE",
		"BG079_POLICE_STATION_INSIDE", 
		"BG080_POLICE_STATION_EVIDENCE_ROOM",
		"BG081_STEEL_SAMURAI_CROSSING_SWORDS",
		0, 0, 0,
		"BG085_TRAIN_STATION",
		"BG086_MAP_OF_GOURD_LAKE",
		"BG087_LOTTAS_PHOTO_ENLARGED",
		"BG088_INCIDENT_FROM_DL_6",
		"BG089_NEWSPAPER_ABOUT_GOURDY",
		"BG090_LARRY_WITH_BALLOON",
		"BG091_BALLOON_HITTING_LAKE",
		"BG092_LARRY_SEARCHING_FOR_BALLOON",
		"BG093_SCHOOL_COURT",
		"BG094_LOTTAS_PHOTO",
		"BG095_SCHOOL_PHOENIX",
		"BG096_SCHOOL_EDGEWORTH",
		"BG097_SCHOOL_LARRY",
		"BG098_YANNI_ATTACKING_VICTIM",
		"BG099_YANNI_AND_EDGEWORTH_ON_BOAT",
		"BG100_EDGEWORTH_INSIDE_ELEVATOR",
		"BG101_EDGEWORTH_THROWING_GUN",
		"BG102_VON_KARMA_BEING_SHOT",
		"BG103_VON_KARMA_ENTERING_ELEVATOR",
		"BG104_MAYA_LEAVING_AT_STATION",
		"BG105_WINNING_PARTY_AFTER_CREDITS",
		"BG106_BOAT_WITH_SINGLE_PASSENGER",
		"BG107_MAN_WITH_GUN",
		"BG108_EDGEWORTH_WITH_GUN",
		"BG109_CAPCOM_LOGO_BLACK_AND_WHITE",
		0, 0, 0,
		"BG113_POLICE_STATION_ENTRANCE",
		"BG114_EDGEWORTHS_OFFICE",
		"BG115_PARKING_GARAGE",
		"BG116_GANTS_OFFICE",
		"BG117_EVIDENCE_LOCKER_ROOM",
		"BG118_POLICE_STATION_SECURITY_ROOM",
		"BG119_MAP_OF_PARKING_GARAGE",
		"BG120_LANA_ATTACKING_GOODMAN",
		"BG121_LANA_IN_GARAGE",
		"BG122_ANGEL_WITH_LANA",
		"BG123_EDGEWORTHS_CAR_TRUNK",
		"BG124_GOODMANS_NOTE",
		"BG125_KEY_CARD_LOG_BLANK",
		"BG126_MEEKINS_WITH_GOODMAN_AT_LOCKERS",
		0,
		"BG128_BLOODY_PRINT_ON_LOCKER",
		"BG129_LUMINOL_PRINT_ON_LOCKER",
		"BG130_HAND_PRINT_ON_CLOTH",
		0, 0, 0, 0, 0, 0, 0, 0, 0,
		"BG140_CONTRADICTION_OF_THE_LAW",
		0,
		"BG142_VASE_CLOSEUP_OF_WRITING",
		0,
		"BG144_EVIDENCE_LOCKERS_CLOSEUP",
		"BG145_EVIDENCE_LOCKERS_CLOSEUP_OF_PRINT",
		"BG146_EVIDENCE_LOCKERS_LEFT_LUMINOL_0",
		"BG147_EVIDENCE_LOCKERS_LEFT_LUMINOL_1",
		0, 0,
		0, 0, 0, 
		"BG153_VASE_BREAK_1",
		"BG154_VASE_BREAK_2",
		"BG155_VASE_BREAK_3",
		"BG156_BACKLIT_BADGER",
		"BG157_PARKING_GARAGE_BACKGROUND",
		0,
		"BG159_MAP_OF_EVIDENCE_LOCKER_ROOM",
		"BG160_VASE_CLOSEUP_WITH_BLOODY_WRITING_COMPLETE",
		"BG161_KEY_CARD_LOG_2",
		"BG162_KEY_CARD_LOG_3",
		0, 0, 0, 0,
		"BG167_KURAIN_VILLAGE",
		0, 0,
		//170
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		//180
		0,
		"BG181_STATUE_IN_GANTS_OFFICE",
		"BG182_LANA_AND_GANT",
		"BG183_SL_9_MURDERER_DARKE",
		"BG184_SL_9_INVESTIGATION_GROUP",
		"BG185_SL_9_GANT_LANA_NEIL_WITH_TROPHY",
		"BG186_SL_9_MURDER_SCENE",
		"BG187_SL_9_LANA_WITH_UNCONCIOUS_EMA",
		"BG188_SL_9_DEAD_NEIL_WITH_MURDERER",
		"BG189_SL_9_EMAS_DRAWING",
		"BG190_SL_9_EMAS_DRAWING_PEOPLE",
		"BG191_SL_9_EMAS_DRAWING_VASE",
		0, 0, 0, 0, 0,
		"BG197_VASE_WITH_BLOODY_WRITING",
		0,
		"BG199_NEIL_IMPALED_ON_STATUE_PHOTO",
		"BG200_JAPANESE_KEYPAD", // matching language is just patched on?
		"BG201_EVIDENCE_LOCKERS_UNTOUCHED",
		"BG202_RED_BADGER_HEAD",
		"BG203_LANA_HUGGING_EMA",
		"BG204_YOUNG_LANA_WITH_EMA",
		0, 0, 0, 0, 0,
		//210
		0,
		"BG211_GANTS_OFFICE_AGAIN", //211 this is gants office again?
		"BG212_VASE_CLOSEUP_WITH_MISSING_PIECE",
		0, 0, 0, 0, 0, 0, 0,
		//220
		0,
		"BG221_VASE_ANGLED_AS_BADGER",
		"BG222_KEYPAD_DISPLAY",
		"BG223_SAFE_AT_GANTS_OFFICE_0",
		"BG224_SAFE_AT_GANTS_OFFICE_1",
		"BG225_SAFE_AT_GANTS_OFFICE_2",
		"BG226_VASE_MISSING_PIECE_COMPLETE_WRITING",
		0,
		"BG228_CITY_IN_INTRO",
		0,
		"BG230_BACKGROUND_FOR_DANCING_BADGER",
		0,
		"BG232_KING_OF_PROSECUTORS_TROPHY",
		0,
		"BG234_EMAS_DRAWING_VERTICAL",
		"BG235_POLICE_STATION_ENTRANCE_NO_BADGER",
		"BG236_NEIL_FLYING_TOWARDS_STATUE_1",
		"BG237_NEIL_FLYING_TOWARDS_STATUE_2",
		"BG238_NEIL_FLYING_TOWARDS_STATUE_3",
		0,
		"BG240_GOODMAN_IN_CAR_TRUNK",
		0, 0, 0, 0, 0, 0, 0, 0, 0,
		//250
		0, 0, 0, 0, 0,
		"BG255_SPC_BLACK_SCREEN", //255
		0, 0, 0, 0,
		
		[4095] = "BG4095_SPC_BLACK_SCREEN"
		// 32884 seems to be gants office yet again?
	},
	{
		/* phoenix 2 to be done */
		0,
		0,
		"BG002_CAPCOM_LOGO_GRAYSCALE",
		"BG003_DEFENSE_LOBBY",
		"BG004_COURT_DEFENSE",
		"BG005_COURT_PROSECUTION",
		"BG006_COURT_STAND",
		"BG007_COURT_JUDGE",
		"BG008_COURT_DEFENSE_PARTNER",
		"BG009_COURTROOM_FULL_VIEW",
		0,
		"BG011_GAVEL_SLAM",
		0,
		0,
		0,
		0,
		"BG016_SPEEDLINES",
		"BG017_DETENTION_CENTER",
		"BG018_PHOENIX_OFFICE",
		"BG019_POLICE_HQ_INSIDE",
		0,
		"BG021_PHOTO_OF_DEAD_DUSTIN",
		"BG022_PHOTO_OF_MESSAGE_IN_SAND",
		"BG023_MAGGEY_WITH_VICTIM",
		"BG024_MAGGEY_SEES_VICTIM_AND_CULPRIT",
		0,
		"BG026_PHOENIX_NIGHTMARE",
		"BG027_CULPRIT_AFTER_HITTING_PHOENIX",
		"BG028_KURAIN",
		"BG029_FEY_MANOR_MAIN_HALL",
		"BG030_FEY_MANOR_SUMMONING_ROOM",
		"BG031_FEY_MANOR_WINDING_WAY",
		"BG032_FEY_MANOR_SPARE_ROOM",
		0,
		"BG034_HOTTI_CLINIC",
		"BG035_CAR_DRIVING",
		"BG036_CAR_ACCIDENT",
		"BG037_PHOENIX_WITH_MAYA_IN_DETENTION",
		0,
		0,
		0,
		0,
		"BG042_MAP_OF_SUMMONING_ROOM",
		"BG043_MAP_OF_FEY_MANOR",
		"BG044_CAR_LIGHTS_RIGHT",
		"BG045_DEAD_MIA_FROM_PHOENIX_1",
		"BG046_MAYA_WITH_VICTIM",
		"BG047_NURSE_AT_HOSPITAL",
		"BG048_MAYAS_COSTUME",
		"BG049_PHOTO_OF_CULPRIT_BACK",
		"BG050_PHOTO_OF_CULPRIT_FRONT",
		"BG051_PHOTO_OF_MIA_SUMMONED_BY_MAYA",
		"BG052_PEARL_FIXING_URN",
		"BG053_MORGAN_WITH_PHOTO",
		"BG054_CULPRIT_AND_INI",
		"BG055_INI_WITH_KNOCKED_OUT_MAYA",
		"BG056_BOX_BEHIND_SCREEN",
		"BG057_VICTIM_WITH_GUN",
		"BG058_MAYA_AND_MIA_SUMMONED_BY_PEARL",
		"BG059_CIRCUS_TENT",
		"BG060_CIRCUS_CAFETERIA",
		"BG061_MR._BERRIES_OFFICE",
		0,
		"BG063_CIRCUS_ENTRANCE_NIGHT",
		"BG064_CIRCUS_COURTYARD",
		"BG065_MOES_ROOM",
		"BG066_ACROS_ROOM",
		0,
		0,
		"BG069_CIRCUS_FULL_VIEW",
		"BG070_MAX_GALACTICA_INTRO",
		0,
		"BG072_MAX_GALACTICA_POSTER",
		"BG073_PHOTO_OF_MAX_WITH_AWARD",
		"BG074_MAX_NEGOTIATING_WITH_VICTIM",
		"BG075_MAP_OF_CIRCUS",
		"BG076_PHOTO_OF_VICTIM_OVER_BOX",
		"BG077_VICTIM_SLUMPED_OVER_BOX",
		"BG078_VICTIM_LIFTING_BOX",
		"BG079_VICTIM_HIT_WITH_STATUE",
		"BG080_LION_WITH_ACROS_BROTHER",
		"BG081_VICTIM_SEEN_BY_TRILO",
		"BG082_ACRO_SEEING_MAX",
		"BG083_MAX_STATUE",
		"BG084_ACRO_DROPPING_STATUE",
		"BG085_MAX_GRABBING_BOTTLE",
		"BG086_ACRO_LOWER_HALF_AT_COURT",
		"BG087_EDGEWORTH_AT_AIRPORT",
		"BG088_GATEWATER_HOTEL_BALLROOM",
		"BG089_GATEWATER_HOTEL_HALLWAY",
		"BG090_GATEWATER_HOTEL_ENGARDES_ROOM",
		"BG091_GATEWATER_HOTEL_CORRIDAS_ROOM",
		0,
		"BG093_GATEWATER_HOTEL_LOBBY",
		"BG094_ENGARDES_LIVING_ROOM",
		"BG095_SECRET_ROOM",
		"BG096_WINE_CELLAR",
		"BG097_CLOUDS",
		"BG098_JAMMIN_NINJA_POSTER",
		"BG099_AIRPORT",
		"BG100_PHOTO_OF_VICTIM",
		0,
		"BG102_PHOTO_OF_ANDREWS_IN_COSTUME",
		"BG103_NICKEL_SAMURAI_POSTER",
		"BG104_JUAN_AT_SUICIDE",
		"BG105_ANDREWS_DRESSING_UP_IN_COSTUME",
		"BG106_ANDREWS_WAKING_UP_MATT",
		"BG107_ENGARDE_WITH_CELESTE_BASE",
		"BG108_EDGEWORTH_WITH_GUN_FROM_PHOENIX_1",
		"BG109_ENGARDE_WITH_BUTLER",
		"BG110_FRANZISKA_ENTERING_COURT",
		"BG111_BUTLER_RECIEVING_BEAR",
		"BG112_PHOENIX_WITH_MAYA_AND_PEARL",
		"BG113_CALLING_CARD_WITH_DRAWING",
		"BG114_PHOENIX_LEAVING_BAD_END",
		"BG115_ANDREWS_FINDING_JUAN",
		"BG116_DE_KILLER_CALLING_CARD",
		"BG117_STEEL_SAMURAI_POSTER",
		0,
		"BG119_YOUNG_EDGEWORTH_FROM_PHOENIX_1",
		"BG120_HEROES_LINEUP",
		"BG121_NICKEL_SAMURAI_SPOTLIGHT",
		"BG122_NICKEL_SAMURAI_WITH_FAN",
		
		
		[4095] = "BGSPC_BLACK_SCREEN",
	},
	{
		/* phoenix 3 to be done */
		0
	},
	{
		/* apollo to be done */
		0
	}
};

char *musicfading[2] = {
	"FADE_OUT", "FADE_IN"
};

char *musicpause[2] = {
	"MUSIC_PAUSE", "MUSIC_PLAY"
};

char *soundplay[2] = {
	"SOUND_STOP", "SOUND_START"
};

char *showside[2] = {
	"SHOW_LEFT", "SHOW_RIGHT"
};

char *testimonypress[2] = {
	"SHOWBOX", "HIDEBOX"
};

char *fademode[6] = {
	"FADE_NONE", "FADE_FROM_BLACK", "FADE_TO_BLACK", "FADE_FROM_WHITE", "FADE_TO_WHITE", "FADE_UNK5"
};

char *animationstate[2] = {
	"ANIM_STOP", "ANIM_START"
};

/* 1024 is a placeholder */
char *personanimations[4][1024] = {
	/* phoenix 1 */
	{
		/* placeholder */
		"ANIM000_NONE",
		/* file 000 */
		"ANIM001_DEFENSE_PHOENIX_NORMAL_IDLE",
		"ANIM002_DEFENSE_PHOENIX_NORMAL_TALKING",
		"ANIM003_DEFENSE_PHOENIX_THINKING_IDLE",
		"ANIM004_DEFENSE_PHOENIX_THINKING_TALKING",
		"ANIM005_DEFENSE_PHOENIX_NOD",
		"ANIM006_DEFENSE_PHOENIX_SHAKE_HEAD",
		/* file 001 */
		"ANIM007_DEFENSE_PHOENIX_SLAM_DESK",
		"ANIM008_DEFENSE_PHOENIX_SLAM_IDLE",
		"ANIM009_DEFENSE_PHOENIX_SLAM_TALKING",
		/* file 002 */
		"ANIM010_DEFENSE_PHOENIX_POINT_OBJECTION",
		"ANIM011_DEFENSE_PHOENIX_POINT_IDLE",
		"ANIM012_DEFENSE_PHOENIX_POINT_TALKING",
		/* file 003 */
		"ANIM013_DEFENSE_PHOENIX_DOCUMENT_IDLE",
		"ANIM014_DEFENSE_PHOENIX_DOCUMENT_TALKING",
		/* file 004 */
		"ANIM015_DEFENSE_PHOENIX_SWEAT_IDLE",
		"ANIM016_DEFENSE_PHOENIX_SWEAT_TALKING",
		/* file 005 */
		"ANIM017_DEFENSE_PHOENIX_SHOCK",
		/* file 006 */
		"ANIM018_DEFENSE_PHOENIX_EMBARRASSED_IDLE",
		"ANIM019_DEFENSE_PHOENIX_EMBARRASSED_TALKING",
		/* file 007 */
		"ANIM020_DEFENSE_PHOENIX_HEART_EYES",
		"ANIM021_DEFENSE_PHOENIX_TOUPET_HIT",
		/* file 008 */
		"ANIM022_DEFENSE_PHOENIX_CONFIDENT_IDLE",
		"ANIM023_DEFENSE_PHOENIX_CONFIDENT_TALKING",
		/* file 009 */
		"ANIM024_MAYA_SAD_IDLE",
		"ANIM025_MAYA_SAD_TALKING",
		"ANIM026_MAYA_THINKING_IDLE",
		"ANIM027_MAYA_THINKING_TALKING",
		"ANIM028_MAYA_CONFIDENT_IDLE",
		"ANIM029_MAYA_CONFIDENT_TALKING",
		"ANIM030_MAYA_SURPRISED_IDLE",
		"ANIM031_MAYA_SURPRISED_TALKING",
		/* file 010 */
		"ANIM032_MAYA_NORMAL_IDLE",
		"ANIM033_MAYA_NORMAL_TALKING",
		"ANIM034_MAYA_SHOCK",
		/* file 011 */
		"ANIM035_MAYA_DEJECTED_IDLE",
		"ANIM036_MAYA_DEJECTED_TALKING",
		"ANIM037_MAYA_TEARS_IDLE",
		"ANIM038_MAYA_TEARS_TALKING",
		"ANIM039_MAYA_PUMPED_IDLE",
		"ANIM040_MAYA_PUMPED_TALKING",
		"ANIM041_MAYA_LIGHTSHOCK_IDLE",
		"ANIM042_MAYA_LIGHTSHOCK_TALKING",
		"ANIM043_MAYA_POUTING_IDLE",
		"ANIM044_MAYA_POUTING_TALKING",
		"ANIM045_MAYA_CRYING",
		/* file 012 */
		"ANIM046_MAYA_HAPPY_IDLE",
		"ANIM047_MAYA_HAPPY_TALKING",
		"ANIM048_MAYA_NOD",
		/* file 013 */
		"ANIM049_DEFENSE_MAYA_NORMAL_IDLE",
		"ANIM050_DEFENSE_MAYA_NORMAL_TALKING",
		"ANIM051_DEFENSE_MAYA_ANXIOUS_IDLE",
		"ANIM052_DEFENSE_MAYA_ANXIOUS_TALKING",
		"ANIM053_DEFENSE_MAYA_DEJECTED_IDLE",
		"ANIM054_DEFENSE_MAYA_DEJECTED_TALKING",
		"ANIM055_DEFENSE_MAYA_THINKING_IDLE",
		"ANIM056_DEFENSE_MAYA_THINKING_TALKING",
		"ANIM057_DEFENSE_MAYA_HOPING_IDLE",
		"ANIM058_DEFENSE_MAYA_HOPING_TALKING",
		/* file 014 */
		"ANIM059_SUMMONED_MIA_NORMAL_IDLE",
		"ANIM060_SUMMONED_MIA_NORMAL_TALKING",
		"ANIM061_SUMMONED_MIA_ANXIOUS_IDLE",
		"ANIM062_SUMMONED_MIA_ANXIOUS_TALKING",
		"ANIM063_SUMMONED_MIA_HAPPY_IDLE",
		"ANIM064_SUMMONED_MIA_HAPPY_TALKING",
		"ANIM065_SUMMONED_MIA_SURPRISED_IDLE",
		"ANIM066_SUMMONED_MIA_SURPRISED_TALKING",
		/* file 015 */
		"ANIM067_DEFENSE_SUMMONED_MIA_NORMAL_IDLE",
		"ANIM068_DEFENSE_SUMMONED_MIA_NORMAL_TALKING",
		"ANIM069_DEFENSE_SUMMONED_MIA_UNIMPRESSED_IDLE",
		"ANIM070_DEFENSE_SUMMONED_MIA_UNIMPRESSED_TALKING",
		"ANIM071_DEFENSE_SUMMONED_MIA_THINKING_IDLE",
		"ANIM072_DEFENSE_SUMMONED_MIA_THINKING_TALKING",
		"ANIM073_DEFENSE_SUMMONED_MIA_DEJECTED_IDLE",
		"ANIM074_DEFENSE_SUMMONED_MIA_DEJECTED_TALKING",
		"ANIM075_DEFENSE_SUMMONED_MIA_NOD",
		"ANIM076_DEFENSE_SUMMONED_MIA_SHAKE_HEAD",
		/* file 016 */
		"ANIM077_MIA_NORMAL_IDLE",
		"ANIM078_MIA_NORMAL_TALKING",
		"ANIM079_MIA_HAPPY_IDLE",
		"ANIM080_MIA_HAPPY_TALKING",
		"ANIM081_MIA_SURPRISED_IDLE",
		"ANIM082_MIA_SURPRISED_TALKING",
		"ANIM083_MIA_WINK",
		/* file 017 */
		"ANIM084_DEFENSE_MIA_NORMAL_IDLE",
		"ANIM085_DEFENSE_MIA_NORMAL_TALKING",
		"ANIM086_DEFENSE_MIA_SHOCK_IDLE",
		"ANIM087_DEFENSE_MIA_SHOCK_TALKING",
		"ANIM088_DEFENSE_MIA_DEJECTED_IDLE",
		"ANIM089_DEFENSE_MIA_DEJECTED_TALKING",
		"ANIM090_DEFENSE_MIA_SAD_IDLE",
		"ANIM091_DEFENSE_MIA_SAD_TALKING",
		/* file 018 */
		"ANIM092_JUDGE_NORMAL_IDLE",
		"ANIM093_JUDGE_NORMAL_TALKING",
		"ANIM094_JUDGE_NOD",
		"ANIM095_JUDGE_SHAKE_HEAD",
		"ANIM096_JUDGE_SERIOUS_IDLE",
		"ANIM097_JUDGE_SERIOUS_TALKING",
		"ANIM098_JUDGE_SURPRISED_IDLE",
		"ANIM099_JUDGE_SURPRISED_TALKING",
		"ANIM100_JUDGE_CLOSED_EYES",
		/* file 019 */
		"ANIM101_PROSECUTION_EDGEWORTH_NORMAL_IDLE",
		"ANIM102_PROSECUTION_EDGEWORTH_NORMAL_TALKING",
		"ANIM103_PROSECUTION_EDGEWORTH_DOCUMENT_IDLE",
		"ANIM104_PROSECUTION_EDGEWORTH_DOCUMENT_TALKING",
		"ANIM105_PROSECUTION_EDGEWORTH_DELIGHTED_ANIM",
		"ANIM106_PROSECUTION_EDGEWORTH_DELIGHTED_IDLE",
		/* file 020 */
		"ANIM107_PROSECUTION_EDGEWORTH_POINTING_IDLE",
		"ANIM108_PROSECUTION_EDGEWORTH_POINTING_TALKING",
		"ANIM109_PROSECUTION_EDGEWORTH_THINKING_IDLE",
		"ANIM110_PROSECUTION_EDGEWORTH_THINKING_TALKING",
		/* file 021 */
		"ANIM111_PROSECUTION_EDGEWORTH_SLAM_DESK",
		"ANIM112_PROSECUTION_EDGEWORTH_SLAM_IDLE",
		"ANIM113_PROSECUTION_EDGEWORTH_SLAM_TALKING",
		"ANIM114_PROSECUTION_EDGEWORTH_FRUSTRATED_IDLE",
		"ANIM115_PROSECUTION_EDGEWORTH_FRUSTRATED_TALKING",
		/* file 022 */
		"ANIM116_PROSECUTION_EDGEWORTH_CONFIDENT_IDLE",
		"ANIM117_PROSECUTION_EDGEWORTH_CONFIDENT_TALKING",
		"ANIM118_PROSECUTION_EDGEWORTH_SHAKE_HEAD",
		/* file 023 */
		"ANIM119_PROSECUTION_EDGEWORTH_SHOCK",
		/* file 024 */
		"ANIM120_PROSECUTION_EDGEWORTH_BOW",
		/* file 025 */
		"ANIM121_EDGEWORTH_NORMAL_IDLE",
		"ANIM122_EDGEWORTH_NORMAL_TALKING",
		"ANIM123_EDGEWORTH_ANGRY_IDLE",
		"ANIM124_EDGEWORTH_ANGRY_TALKING",
		"ANIM125_EDGEWORTH_THINKING_IDLE",
		"ANIM126_EDGEWORTH_THINKING_TALKING",
		"ANIM127_EDGEWORTH_OFFSIDE_IDLE",
		"ANIM128_EDGEWORTH_OFFSIDE_TALKING",
		"ANIM129_EDGEWORTH_CONFIDENT_IDLE",
		"ANIM130_EDGEWORTH_CONFIDENT_TALKING",
		/* file 026 */
		"ANIM131_EDGEWORTH_ANXIOUS_IDLE",
		"ANIM132_EDGEWORTH_ANXIOUS_TALKING",
		"ANIM133_EDGEWORTH_FRUSTRATED_IDLE",
		"ANIM134_EDGEWORTH_FRUSTRATED_TALKING",
		/* file 027 */
		"ANIM135_EDGEWORTH_POINT_IDLE",
		"ANIM136_EDGEWORTH_POINT_OBJECTION",
		/* file 028 */
		"ANIM137_EDGEWORTH_SHOCK_IDLE",
		"ANIM138_EDGEWORTH_SHOCK_ANIM",
		/* file 029 */
		"ANIM139_GUMSHOE_NORMAL_IDLE",
		"ANIM140_GUMSHOE_NORMAL_TALKING",
		"ANIM141_GUMSHOE_THINKING_IDLE",
		"ANIM142_GUMSHOE_THINKING_TALKING",
		"ANIM143_GUMSHOE_HAPPY_IDLE",
		"ANIM144_GUMSHOE_HAPPY_TALKING",
		"ANIM145_GUMSHOE_CONFIDENT_IDLE",
		"ANIM146_GUMSHOE_CONFIDENT_TALKING",
		"ANIM147_GUMSHOE_SAD_IDLE",
		"ANIM148_GUMSHOE_SAD_TALKING",
		/* file 030 */
		"ANIM149_GUMSHOE_ANGRY_IDLE",
		"ANIM150_GUMSHOE_ANGRY_TALKING",
		"ANIM151_GUMSHOE_DEJECTED_IDLE",
		"ANIM152_GUMSHOE_DEJECTED_TALKING",
		/* file 031 */
		"ANIM153_GUMSHOE_PUMPED_IDLE",
		"ANIM154_GUMSHOE_PUMPED_TALKING",
		/* file 032 */
		"ANIM155_GUMSHOE_HEADSCRATCH_IDLE",
		"ANIM156_GUMSHOE_HEADSCRATCH_ANIM",
		/* file 033 */
		"ANIM157_WHITE_SHRUG",
		/* file 034 */
		"ANIM158_WHITE_THINKING_IDLE",
		"ANIM159_WHITE_THINKING_TALKING",
		"ANIM160_WHITE_NORMAL_IDLE",
		"ANIM161_WHITE_NORMAL_TALKING",
		/* file 035 */
		"ANIM162_WHITE_SWEAT_IDLE",
		"ANIM163_WHITE_SWEAT_TALKING",
		"ANIM164_WHITE_SCARED_IDLE",
		"ANIM165_WHITE_SCARED_TALKING",
		/* file 036 */
		"ANIM166_WHITE_SHOWOFF",
		/* file 037 */
		"ANIM167_WHITE_CONFIDENT_IDLE",
		"ANIM168_WHITE_CONFIDENT_TALKING",
		/* file 038 */
		"ANIM169_WHITE_BREAKDOWN_PRE",
		"ANIM170_WHITE_BREAKDOWN_ANIM",
		"ANIM171_WHITE_BREAKDOWN_POST",
		/* file 039 */
		"ANIM172_MAY_NORMAL_IDLE",
		"ANIM173_MAY_NORMAL_TALKING",
		"ANIM174_MAY_ANGRY_IDLE",
		"ANIM175_MAY_ANGRY_TALKING",
		"ANIM176_MAY_THINKING_IDLE",
		"ANIM177_MAY_THINKING_TALKING",
		"ANIM178_MAY_SAD_IDLE",
		"ANIM179_MAY_SAD_TALKING",
		"ANIM180_MAY_EVIL_STATIC",
		"ANIM181_MAY_CRYING",
		/* file 040 */
		"ANIM182_MAY_SHOWOFF",
		"ANIM183_MAY_EVIL_IDLE",
		"ANIM184_MAY_EVIL_TALKING",
		"ANIM185_MAY_EVIL_SIDE_IDLE",
		"ANIM186_MAY_EVIL_SIDE_TALKING",
		/* file 041 */
		"ANIM187_MAY_BREAKDOWN",
		/* file 042 */
		"ANIM188_PROSECUTION_PAYNE_NORMAL_IDLE",
		"ANIM189_PROSECUTION_PAYNE_NORMAL_TALKING",
		/* file 043 */
		"ANIM190_BELLBOY_EMBARRASSED_IDLE",
		"ANIM191_BELLBOY_EMBARRASSED_TALKING",
		"ANIM192_BELLBOY_NORMAL_IDLE",
		"ANIM193_BELLBOY_NORMAL_TALKING",
		/* file 044 */
		"ANIM194_BUTZ_NORMAL_IDLE",
		"ANIM195_BUTZ_NORMAL_TALKING",
		"ANIM196_BUTZ_ANXIOUS",
		/* file 045 */
		"ANIM197_BUTZ_CRYING_IDLE",
		"ANIM198_BUTZ_CRYING_TALKING",
		/* file 046 */
		"ANIM199_BUTZ_HAPPY_IDLE",
		"ANIM200_BUTZ_HAPPY_TALKING",
		/* file 047 */
		"ANIM201_COSTUME_BUTZ_HAPPY_IDLE",
		"ANIM202_COSTUME_BUTZ_HAPPY_TALKING",
		"ANIM203_COSTUME_BUTZ_ANGRY_IDLE",
		"ANIM204_COSTUME_BUTZ_ANGRY_TALKING",
		"ANIM205_COSTUME_BUTZ_SAD_IDLE",
		"ANIM206_COSTUME_BUTZ_SAD_TALKING",
		"ANIM207_COSTUME_BUTZ_WITH_HEAD",
		/* file 048 */
		"ANIM208_BUTZ_EMBARRASSED_IDLE",
		"ANIM209_BUTZ_EMBARRASSED_TALKING",
		/* file 049 */
		"ANIM210_BUTZ_ANGRY_IDLE",
		"ANIM211_BUTZ_ANGRY_TALKING",
		/* file 050 */
		"ANIM213_BUTZ_CONFIDENT_IDLE",
		"ANIM214_BUTZ_CONFIDENT_TALKING",
		/* file 051 */
		"ANIM215_BUTZ_THINKING_IDLE",
		"ANIM216_BUTZ_THINKING_TALKING",
		"ANIM217_BUTZ_SHOCK_TALKING",
		"ANIM218_BUTZ_SHOCK_IDLE",
		/* file 052 */
		"ANIM219_BUTZ_THUMBSUP_IDLE",
		"ANIM220_BUTZ_THUMBSUP_TALKING",
		/* file 053 */
		"ANIM221_SAHWIT_NORMAL_IDLE",
		"ANIM222_SAHWIT_NORMAL_TALKING",
		"ANIM223_SAHWIT_ANXIOUS_IDLE",
		"ANIM224_SAHWIT_ANXIOUS_TALKING",
		/* file 054 */
		"ANIM225_SAHWIT_ANGRY_IDLE",
		"ANIM226_SAHWIT_ANGRY_TALKING",
		/* file 055 */
		"ANIM227_SAHWIT_NOHAIR_IDLE",
		"ANIM228_SAHWIT_NOHAIR_TALKING",
		"ANIM229_SAHWIT_BREAKDOWN_ANIM",
		"ANIM230_SAHWIT_BREAKDOWN_POST",
		/* file 056 */
		"ANIM231_SAHWIT_TOUPET_THROW",
		/* file 057 */
		"ANIM232_SAHWIT_SHOCK",
		/* file 058 */
		"ANIM233_GROSSBERG_NORMAL_IDLE",
		"ANIM234_GROSSBERG_NORMAL_TALKING",
		"ANIM235_GROSSBERG_SAD_IDLE",
		"ANIM236_GROSSBERG_SAD_TALKING",
		/* file 059 */
		"ANIM237_OLDBAG_NORMAL_IDLE",
		"ANIM238_OLDBAG_NORMAL_TALKING",
		"ANIM239_OLDBAG_EXCITED_IDLE",
		"ANIM240_OLDBAG_EXCITED_TALKING",
		"ANIM241_OLDBAG_CONFIDENT_IDLE",
		"ANIM242_OLDBAG_CONFIDENT_TALKING",
		"ANIM243_OLDBAG_SHOCK",
		/* file 060 */
		"ANIM244_OLDBAG_WAVEOFF_IDLE",
		"ANIM245_OLDBAG_WAVEOFF_TALKING",
		"ANIM246_OLDBAG_INLOVE_IDLE",
		"ANIM247_OLDBAG_INLOVE_TALKING",
		/* file 061 */
		"ANIM248_NICHOLS_NORMAL_IDLE",
		"ANIM249_NICHOLS_NORMAL_TALKING",
		"ANIM250_NICHOLS_SECRETIVE_IDLE",
		"ANIM251_NICHOLS_SECRETIVE_TALKING",
		"ANIM252_NICHOLS_CARDS_IDLE",
		"ANIM253_NICHOLS_CARDS_TALKING",
		/* file 062 */
		"ANIM254_POWERS_NORMAL_IDLE",
		"ANIM255_POWERS_SAD_TALKING",
		/* file 063 */
		"ANIM256_POWERS_HAPPY_IDLE",
		"ANIM257_POWERS_HAPPY_TALKING",
		"ANIM258_POWERS_EXHAUSTED_IDLE",
		"ANIM259_POWERS_EXHAUSTED_TALKING",
		/* file 064 */
		"ANIM260_MANELLA_NORMAL_IDLE",
		"ANIM261_MANELLA_NORMAL_TALKING",
		"ANIM262_MANELLA_DEJECTED_IDLE",
		"ANIM263_MANELLA_DEJECTED_TALKING",
		"ANIM264_MANELLA_FREAKY_IDLE",
		"ANIM265_MANELLA_FREAKY_TALKING",
		/* file 065 */
		"ANIM267_MANELLA_SHOCK",
		/* file 066 */
		"ANIM268_MANELLA_SCARED_IDLE",
		"ANIM269_MANELLA_SCARED_TALKING",
		/* file 067 */
		"ANIM270_MANELLA_THINKING_IDLE",
		"ANIM271_MANELLA_THINKING_TALKING",
		/* file 068 */
		"ANIM272_VASQUEZ_NORMAL_IDLE",
		"ANIM273_VASQUEZ_NORMAL_TALKING",
		"ANIM274_VASQUEZ_SHOCK",
		"ANIM275_VASQUEZ_CONFIDENT_IDLE",
		"ANIM276_VASQUEZ_CONFIDENT_TALKING",
		"ANIM277_VASQUEZ_SURPRISE_ANIM",
		"ANIM278_VASQUEZ_SURPRISE_IDLE",
		/* file 069 */
		"ANIM279_VASQUEZ_EVIL_IDLE",
		"ANIM280_VASQUEZ_EVIL_TALKING",
		"ANIM281_VASQUEZ_BREAKDOWN_ANIM",
		"ANIM282_VASQUEZ_BREAKDOWN_PRE",
		"ANIM283_VASQUEZ_REFORMED_IDLE",
		"ANIM284_VASQUEZ_REFORMED_TALKING",
		/* file 070 */
		"ANIM285_HACKINS_HAPPY_IDLE",
		"ANIM286_HACKINS_HAPPY_TALKING",
		"ANIM287_HACKINS_SAD_IDLE",
		"ANIM288_HACKINS_SAD_TALKING",
		"ANIM289_HACKINS_SMUG_IDLE",
		"ANIM290_HACKINS_SMUG_TALKING",
		/* file 071 */
		"ANIM291_HACKINS_ANGRY_IDLE",
		"ANIM292_HACKINS_ANGRY_TALKING",
		/* file 072 */
		"ANIM293_HACKINS_TEARS_IDLE",
		"ANIM294_HACKINS_TEARS_TALKING",
		"ANIM295_HACKINS_CRYING_IDLE",
		"ANIM296_HACKINS_CRYING_TALKING",
		/* file 073 */
		"ANIM297_HACKINS_CAMERA_IDLE",
		"ANIM298_HACKINS_CAMERA_TALKING",
		"ANIM299_HACKINS_POUTING_IDLE",
		"ANIM300_HACKINS_POUTING_TALKING",
		"ANIM301_HACKINS_SCHOCK_ANIM",
		"ANIM302_HACKINS_SCHOCK_IDLE",
		"ANIM303_HACKINS_WITNESS_STAND_NOBOX",
		/* file 074 */
		"ANIM304_BUSTUP_PHOENIX_IDLE",
		"ANIM305_BUSTUP_PHOENIX_TALKING",
		/* file 075 */
		"ANIM306_BUSTUP_EDGEWORTH_IDLE",
		"ANIM307_BUSTUP_EDGEWORTH_TALKING",
		/* file 076 */
		"ANIM308_HART_NORMAL_IDLE",
		"ANIM309_HART_NORMAL_TALKING",
		"ANIM310_HART_EMBARRASSED_IDLE",
		"ANIM311_HART_EMBARRASSED_TALKING",
		"ANIM312_HART_ANGRY_IDLE",
		"ANIM313_HART_ANGRY_TALKING",
		"ANIM314_HART_SHOCK_ANIM",
		"ANIM315_HART_SHOCK_IDLE",
		/* file 077 */
		"ANIM316_HART_DEJECTED_IDLE",
		"ANIM317_HART_DEJECTED_TALKING",
		"ANIM318_HART_CONFIDENT_IDLE",
		"ANIM319_HART_CONFIDENT_TALKING",
		"ANIM320_HART_POUTING_IDLE",
		"ANIM321_HART_POUTING_TALKING",
		"ANIM322_HART_THINKING_IDLE",
		"ANIM323_HART_THINKING_TALKING",
		"ANIM324_HART_HAPPY_IDLE",
		"ANIM325_HART_HAPPY_TALKING",
		/* file 078 */
		"ANIM326_OLDMAN_NORMAL_IDLE",
		"ANIM327_OLDMAN_NORMAL_TALKING",
		"ANIM328_OLDMAN_SLEEP_ANIM",
		"ANIM329_OLDMAN_SLEEP_IDLE",
		"ANIM330_OLDMAN_SLEEP_WAKEUP",
		"ANIM331_OLDMAN_SERIOUS_ANIM",
		"ANIM332_OLDMAN_SERIOUS_IDLE",
		/* file 079 */
		"ANIM333_OLDMAN_OFFSIDE_IDLE",
		"ANIM334_OLDMAN_OFFSIDE_TALKING",
		"ANIM335_OLDMAN_THINKING_IDLE",
		"ANIM336_OLDMAN_THINKING_TALKING",
		/* file 080 */
		"ANIM337_OLDMAN_ANGRY_IDLE",
		"ANIM338_OLDMAN_ANGRY_TALKING",
		"ANIM339_OLDMAN_BREAKDOWN_ANIM",
		"ANIM340_OLDMAN_BREAKDOWN_IDLE",
		/* file 081 */
		"ANIM341_OLDMAN_REFORMED_IDLE",
		"ANIM342_OLDMAN_REFORMED_TALKING",
		"ANIM343_OLDMAN_REFORMED_SAD_IDLE",
		"ANIM344_OLDMAN_REFORMED_SAD_TALKING",
		/* file 082 */
		"ANIM345_PROSECUTION_VONKARMA_NORMAL_IDLE",
		"ANIM346_PROSECUTION_VONKARMA_NORMAL_TALKING",
		"ANIM347_PROSECUTION_VONKARMA_CONFIDENT_IDLE",
		"ANIM348_PROSECUTION_VONKARMA_CONFIDENT_TALKING",
		"ANIM349_PROSECUTION_VONKARMA_ANXIOUS_IDLE",
		"ANIM350_PROSECUTION_VONKARMA_ANXIOUS_TALKING",
		/* file 083 */
		"ANIM351_PROSECUTION_VONKARMA_SHAKE_HEAD_ANIM",
		"ANIM352_PROSECUTION_VONKARMA_SHAKE_HEAD_IDLE",
		/* file 084 */
		"ANIM353_PROSECUTION_VONKARMA_SWEATING_IDLE",
		"ANIM354_PROSECUTION_VONKARMA_SWEATING_TALKING",
		/* file 085 */
		"ANIM355_PROSECUTION_VONKARMA_FINGERSNAP_IDLE",
		"ANIM356_PROSECUTION_VONKARMA_FINGERSNAP_TALKING",
		"ANIM357_PROSECUTION_VONKARMA_FINGERSNAP_ANIM",
		"ANIM358_PROSECUTION_VONKARMA_FINGERSNAP_POST",
		/* file 086 */
		"ANIM359_PROSECUTION_VONKARMA_ENRAGED_ANIM",
		"ANIM360_PROSECUTION_VONKARMA_ENRAGED_IDLE",
		"ANIM361_PROSECUTION_VONKARMA_ENRAGED_POST",
		/* file 087 */
		"ANIM362_VONKARMA_NORMAL_IDLE",
		"ANIM363_VONKARMA_NORMAL_TALKING",
		"ANIM364_VONKARMA_HAPPY_IDLE",
		"ANIM365_VONKARMA_HAPPY_TALKING",
		"ANIM366_VONKARMA_STUNGUN_IDLE",
		"ANIM367_VONKARMA_STUNGUN_TALKING",
		/* file 088 */
		"ANIM368_PROSECUTION_VONKARMA_WALLBANG_ANIM",
		"ANIM369_PROSECUTION_VONKARMA_WALLBANG_IDLE",
		/* file 089 */
		"ANIM370_POLLY_IDLE",
		"ANIM371_POLLY_TALKING",
		/* file 090 */
		"ANIM372_EMA_NORMAL_IDLE",
		"ANIM373_EMA_NORMAL_TALKING",
		"ANIM374_EMA_DEJECTED_IDLE",
		"ANIM375_EMA_DEJECTED_TALKING",
		/* file 091 */
		"ANIM376_EMA_THINKING_IDLE",
		"ANIM377_EMA_THINKING_TALKING",
		/* file 092 */
		"ANIM378_EMA_GLASSES_LIFT",
		"ANIM379_EMA_GLASSES_IDLE",
		"ANIM380_EMA_GLASSES_TALKING",
		/* file 093 */
		"ANIM381_EMA_SAD_IDLE",
		"ANIM382_EMA_SAD_TALKING",
		/* file 094 */
		"ANIM383_EMA_PUMPED_IDLE",
		"ANIM384_EMA_PUMPED_TALKING",
		/* file 095 */
		"ANIM385_EMA_HAPPY_IDLE",
		"ANIM386_EMA_HAPPY_TALKING",
		/* file 096 */
		"ANIM387_EMA_POUTING_IDLE",
		"ANIM388_EMA_POUTING_TALKING",
		/* file 097 */
		"ANIM389_EMA_SURPRISED_IDLE",
		"ANIM390_EMA_SURPRISED_TALKING",
		/* file 098 */
		"ANIM391_EMA_ANXIOUS_IDLE",
		"ANIM392_EMA_ANXIOUS_TALKING",
		/* file 099 */
		"ANIM393_EMA_NOTEPAD_ANIM",
		"ANIM394_EMA_NOTEPAD_IDLE",
		"ANIM395_EMA_NOTEPAD_TALKING",
		/* file 100 */
		"ANIM396_DEFENSE_EMA_NORMAL_IDLE",
		"ANIM397_DEFENSE_EMA_NORMAL_TALKING",
		/* file 101 */
		"ANIM398_DEFENSE_EMA_PUMPED_IDLE",
		"ANIM399_DEFENSE_EMA_PUMPED_TALKING",
		/* file 102 */
		"ANIM400_DEFENSE_EMA_THINKING_IDLE",
		"ANIM401_DEFENSE_EMA_THINKING_TALKING",
		/* file 103 */
		"ANIM401_DEFENSE_EMA_ANXIOUS_IDLE",
		"ANIM402_DEFENSE_EMA_ANXIOUS_TALKING",
		/* file 104 */
		"ANIM403_LANA_NORMAL_IDLE",
		"ANIM404_LANA_NORMAL_TALKING",
		"ANIM405_LANA_SIDELOOK_IDLE",
		"ANIM406_LANA_SIDELOOK_TALKING",
		"ANIM407_LANA_SURPRISED_IDLE",
		"ANIM408_LANA_SURPRISED_TALKING",
		"ANIM409_LANA_SERIOUS_IDLE",
		"ANIM410_LANA_SERIOUS_TALKING",
		/* file 105 */
		"ANIM411_LANA_OFFSIDE_IDLE",
		"ANIM412_LANA_OFFSIDE_TALKING",
		"ANIM413_LANA_BACKSIDE_IDLE",
		"ANIM414_LANA_BACKSIDE_TURNAWAY",
		"ANIM415_LANA_BACKSIDE_TURNBACK",
		/* file 106 */
		"ANIM416_LANA_HAPPY_SMILE",
		"ANIM417_LANA_HAPPY_IDLE",
		"ANIM418_LANA_HAPPY_TALKING",
		/* file 107 */
		"ANIM419_LANA_ANXIOUS_IDLE",
		"ANIM420_LANA_ANXIOUS_TALKING",
		/* file 108 */
		"ANIM421_LANA_ANXIOUS_FINGERBITE",
		/* file 109 */
		"ANIM422_LANA_DESPARATE_IDLE",
		"ANIM423_LANA_DESPARATE_TALKING",
		/* file 110 */
		"ANIM424_MEEKINS_NORMAL_IDLE",
		/* file 111 */
		"ANIM425_MEEKINS_SALUTE_ANIM",
		"ANIM426_MEEKINS_SALUTE_IDLE",
		"ANIM427_MEEKINS_SALUTE_TALKING",
		"ANIM428_MEEKINS_SALUTE_ANIM_DETENTION",
		/* file 112 */
		"ANIM429_MEEKINS_FISTSLAM_ANIM",
		"ANIM430_MEEKINS_FISTSLAM_IDLE",
		"ANIM431_MEEKINS_FISTSLAM_TALKING",
		/* file 113 */
		"ANIM432_MEEKINS_SAD_IDLE",
		"ANIM433_MEEKINS_SAD_TALKING",
		/* file 114 */
		"ANIM434_MEEKINS_MEGAPHONE_IDLE",
		"ANIM435_MEEKINS_MEGAPHONE_TALKING",
		"ANIM436_MEEKINS_MEGAPHONE_HIGH_TALKING",
		/* file 115 */
		"ANIM437_MEEKINS_THINKING_IDLE",
		"ANIM438_MEEKINS_THINKING_TALKING",
		/* file 116 */
		"ANIM439_MEEKINS_SHOCK",
		/* file 117 */
		"ANIM440_STARR_NORMAL_IDLE",
		"ANIM441_STARR_NORMAL_TALKING",
		"ANIM442_STARR_NORMAL_STATIC",
		/* file 118 */
		"ANIM443_STARR_HAPPY_IDLE",
		"ANIM444_STARR_HAPPY_TALKING",
		/* file 119 */
		"ANIM445_STARR_CONFIDENT_IDLE",
		"ANIM446_STARR_CONFIDENT_TALKING",
		"ANIM447_STARR_CONFIDENT_ANIM",
		/* file 120 */
		"ANIM448_STARR_ANXIOUS_IDLE",
		"ANIM449_STARR_ANXIOUS_TALKING",
		/* file 121 */
		"ANIM450_STARR_SERIOUS_IDLE",
		"ANIM451_STARR_SERIOUS_TALKING",
		/* file 122 */
		"ANIM452_STARR_LUNCHBOX_ANIM",
		/* file 123 */
		"ANIM453_STARR_PRESENT_IDLE",
		"ANIM454_STARR_PRESENT_TALKING",
		/* file 124 */
		"ANIM455_STARR_SHOCK",
		/* file 125 */
		"ANIM456_MARSHALL_NORMAL_IDLE",
		"ANIM457_MARSHALL_NORMAL_TALKING",
		/* file 126 */
		"ANIM458_MARSHALL_SHAVE_SHAVING",
		"ANIM459_MARSHALL_SHAVE_IDLE",
		"ANIM460_MARSHALL_SHAVE_TALKING",
		/* file 127 */
		"ANIM461_MARSHALL_NOHAT_IDLE",
		"ANIM462_MARSHALL_NOHAT_TALKING",
		/* file 128 */
		"ANIM463_MARSHALL_DRINK_DRINKING",
		"ANIM464_MARSHALL_DRINK_OPENING",
		"ANIM465_MARSHALL_DRINK_IDLE",
		"ANIM466_MARSHALL_DRINK_TALKING",
		/* file 129 */
		"ANIM467_MARSHALL_ANXIOUS_RIPOFF",
		"ANIM468_MARSHALL_ANXIOUS_IDLE",
		"ANIM469_MARSHALL_ANXIOUS_STATIC"
		"ANIM470_MARSHALL_ANXIOUS_TALKING"
		/* file 130 */
		"ANIM471_MARSHALL_FINGERGUN_IDLE",
		"ANIM472_MARSHALL_FINGERGUN_TALKING",
		/* file 131 */
		"ANIM473_MARSHALL_SHOCK_STATIC1",
		/* file 132 */
		"ANIM474_MARSHALL_SHOCK_STATIC2",
		/* file 133 */
		"ANIM475_MARSHALL_SHOCK_STATIC3",
		/* file 134 */
		"ANIM476_MARSHALL_OUTOFBREATH_ANIM1",
		"ANIM477_MARSHALL_OUTOFBREATH_ANIM2"
		/* file 135 */
		"ANIM478_MARSHALL_SERIOUS_IDLE",
		"ANIM479_MARSHALL_SERIOUS_TALKING",
		/* file 136 */
		"ANIM480_GANT_HAPPY_IDLE",
		"ANIM481_GANT_HAPPY_TALKING",
		"ANIM482_GANT_NORMAL_IDLE",
		"ANIM483_GANT_NORMAL_TALKING",
		"ANIM484_GANT_NORMAL_ANIM",
		/* file 137 */
		"ANIM485_GANT_VERYHAPPY_IDLE",
		"ANIM486_GANT_VERYHAPPY_TALKING",
		/* file 138 */
		"ANIM487_GANT_CLAPPING_SLOW",
		"ANIM488_GANT_CLAPPING_FAST",
		/* file 139 */
		"ANIM489_GANT_HAIRTWIRL_IDLE",
		/* file 140 */
		"ANIM490_GANT_HAIRTWIRL_TALKING",
		/* file 141 */
		"ANIM491_GANT_CONFIDENT_IDLE",
		"ANIM492_GANT_CONFIDENT_TALKING",
		/* file 142 */
		"ANIM493_GANT_ANGRY_IDLE",
		"ANIM494_GANT_ANGRY_TALKING",
		/* file 143 */
		"ANIM495_GANT_DESPARATE_IDLE",
		"ANIM496_GANT_DESPARATE_TALKING",
		/* file 144 */
		"ANIM497_GANT_BREAKDOWN_CLAP1",
		/* file 145 */
		"ANIM498_GANT_BREAKDOWN_CLAP2",
		/* file 146 */
		"ANIM499_GANT_BREAKDOWN_THUNDER",
		/* file 147 */
		"ANIM500_BG000_MAYA",
		/* file 148 */
		"ANIM501_WITNESS_TESTIMONY_ANIM_IT",
		"ANIM502_CROSS_EXAMINATION_ANIM_IT",
		"ANIM503_WITNESS_TESTIMONY_PART1_IT",
		"ANIM504_WITNESS_TESTIMONY_PART2_IT",
		"ANIM505_CROSS_EXAMINATION_PART1_IT",
		"ANIM506_CROSS_EXAMINATION_PART2_IT",
		/* file 149 */
		"ANIM507_WITNESS_TESTIMONY_ANIM_DE",
		"ANIM508_CROSS_EXAMINATION_ANIM_DE",
		"ANIM509_WITNESS_TESTIMONY_PART1_DE",
		"ANIM510_WITNESS_TESTIMONY_PART2_DE",
		"ANIM511_CROSS_EXAMINATION_PART1_DE",
		"ANIM512_CROSS_EXAMINATION_PART2_DE",
		/* file 150 */
		"ANIM513_WITNESS_TESTIMONY_ANIM_ES",
		"ANIM514_CROSS_EXAMINATION_ANIM_ES",
		"ANIM515_WITNESS_TESTIMONY_PART1_ES",
		"ANIM516_WITNESS_TESTIMONY_PART2_ES",
		"ANIM517_CROSS_EXAMINATION_PART1_ES",
		"ANIM518_CROSS_EXAMINATION_PART2_ES",
		/* file 151 */
		"ANIM519_OBJECTION_IT",
		/* file 152 */
		"ANIM520_OBJECTION_DE",
		/* file 153 */
		"ANIM521_OBJECTION_ES",
		/* file 154 */
		"ANIM522_HOLDIT_IT",
		/* file 155 */
		"ANIM523_HOLDIT_DE",
		/* file 156 */
		"ANIM524_HOLDIT_ES",
		/* file 157 */
		"ANIM525_HOLDIT2_IT",
		/* file 158 */
		"ANIM526_HOLDIT2_DE",
		/* file 159 */
		"ANIM527_HOLDIT2_ES",
		/* file 160 */
		"ANIM528_TAKETHAT_IT",
		/* file 161 */
		"ANIM528_TAKETHAT_DE",
		/* file 162 */
		"ANIM528_TAKETHAT_ES",
		/* file 163 */
		"ANIM529_HINT_AREA_IT",
		"ANIM530_HINT_ANSWER_IT",
		"ANIM531_HINT_ARROWS_IT",
		"ANIM532_HINT_LUMINOL_IT",
		"ANIM533_HINT_BLANK_IT",
		"ANIM534_HINT_FINGER_IT",
		"ANIM535_HINT_DUSTING_IT",
		"ANIM536_HINT_FINGERPRINT_IT",
		"ANIM537_HINT_ANSWER2_IT",
		"ANIM538_HINT_SHARD_IT",
		"ANIM539_HINT_VASE_IT",
		"ANIM540_HINT_BLOODLETTER_IT",
		"ANIM541_HINT_LANASPHOTO_IT",
		/* file 164 */
		"ANIM542_HINT_AREA_DE",
		"ANIM543_HINT_ANSWER_DE",
		"ANIM544_HINT_ARROWS_DE",
		"ANIM545_HINT_LUMINOL_DE",
		"ANIM546_HINT_BLANK_DE",
		"ANIM547_HINT_FINGER_DE",
		"ANIM548_HINT_DUSTING_DE",
		"ANIM549_HINT_FINGERPRINT_DE",
		"ANIM550_HINT_ANSWER2_DE",
		"ANIM551_HINT_SHARD_DE",
		"ANIM552_HINT_VASE_DE",
		"ANIM553_HINT_BLOODLETTER_DE",
		"ANIM554_HINT_LANASPHOTO_DE",
		/* file 165 */
		"ANIM555_HINT_AREA_ES",
		"ANIM556_HINT_ANSWER_ES",
		"ANIM557_HINT_ARROWS_ES",
		"ANIM558_HINT_LUMINOL_ES",
		"ANIM559_HINT_BLANK_ES",
		"ANIM560_HINT_FINGER_ES",
		"ANIM561_HINT_DUSTING_ES",
		"ANIM562_HINT_FINGERPRINT_ES",
		"ANIM563_HINT_ANSWER2_ES",
		"ANIM564_HINT_SHARD_ES",
		"ANIM565_HINT_VASE_ES",
		"ANIM566_HINT_BLOODLETTER_ES",
		"ANIM567_HINT_LANASPHOTO_ES",
		/* file 166 */
		"ANIM568_RESULT_IT",
		/* file 167 */
		"ANIM569_RESULT_DE",
		/* file 168 */
		"ANIM570_RESULT_ES",
		/* file 169 */
		"ANIM571_RESULT2_IT",
		/* file 170 */
		"ANIM572_RESULT2_DE",
		/* file 171 */
		"ANIM573_RESULT2_ES",
		/* file 172 */
		"ANIM574_NORESULT_NO_IT",
		/* file 173 */
		"ANIM575_NORESULT_NO_DE",
		/* file 174 */
		"ANIM576_NORESULT_NO_ES",
		/* file 175 */
		"ANIM577_NORESULT_RESULT_IT",
		/* file 176 */
		"ANIM578_NORESULT_RESULT_DE",
		/* file 177 */
		"ANIM579_NORESULT_RESULT_ES",
		/* file 178 */
		"ANIM580_NORESULT_RESULT2_IT",
		/* file 179 */
		"ANIM581_NORESULT_RESULT2_DE",
		/* file 180 */
		"ANIM582_NORESULT_RESULT2_ES",
		/* file 181 */
		"ANIM583_CASE1_INTRO_BLOODSPREAD",
		/* file 182 */
		"ANIM584_CASE2_INTRO_HITANIM",
		/* file 183 */
		"ANIM585_CASE1_INTRO_BLOODDROP",
		/* file 184 */
		"ANIM586_CASE3_INTRO_WARRIOR1",
		/* file 185 */
		"ANIM587_CASE3_INTRO_STEEL_SAMURAI_SHADOW",
		/* file 186 */
		"ANIM588_CASE3_INTRO_STEEL_SAMURAI_POSE",
		/* file 187 */
		"ANIM589_CASE3_INTRO_STICK_THROWN",
		/* file 188 */
		"ANIM590_CASE3_INTRO_FIGHTFX",
		/* file 189 */
		"ANIM591_CASE3_INTRO_TREE_LEFT",
		/* file 190 */
		"ANIM592_CASE4_INTRO_BOAT_LEFT_MAN",
		/* file 191 */
		"ANIM593_CASE4_INTRO_WAVES_CALM",
		/* file 192 */
		"ANIM594_CASE4_INTRO_WAVES_AFTER_PUSH",
		/* file 193 */
		"ANIM595_CASE4_INTRO_MUZZLE_FLASH",
		/* file 194 */
		"ANIM596_CASE5_GARAGE_VIEWCONE_RIGHTLEFT",
		/* file 195 */
		"ANIM597_UNKNOWN_RED_DOTLIGHT",
		/* file 196 */
		"ANIM598_FINGERPRINT_MATCH_PROGRESS00",
		"ANIM599_FINGERPRINT_MATCH_PROGRESS01",
		"ANIM600_FINGERPRINT_MATCH_PROGRESS02",
		"ANIM601_FINGERPRINT_MATCH_PROGRESS03",
		"ANIM602_FINGERPRINT_MATCH_PROGRESS04",
		"ANIM603_FINGERPRINT_MATCH_PROGRESS05",
		"ANIM604_FINGERPRINT_MATCH_PROGRESS06",
		"ANIM605_FINGERPRINT_MATCH_PROGRESS07",
		"ANIM606_FINGERPRINT_MATCH_PROGRESS08",
		"ANIM607_FINGERPRINT_MATCH_PROGRESS09",
		"ANIM608_FINGERPRINT_MATCH_PROGRESS10",
		"ANIM609_FINGERPRINT_MATCH_PROGRESS11",
		"ANIM610_FINGERPRINT_MATCH_PROGRESS12",
		"ANIM611_FINGERPRINT_MATCH_PROGRESS13",
		"ANIM612_FINGERPRINT_MATCH_PROGRESS14",
		"ANIM613_FINGERPRINT_MATCH_PROGRESS15",
		"ANIM614_FINGERPRINT_MATCH_PROGRESS16",
		/* file 197 */
		"ANIM615_FINGERPRINT_STATUS_COMPARE_IT",
		"ANIM616_FINGERPRINT_STATUS_COMPLETE_IT",
		/* file 198 */
		"ANIM617_FINGERPRINT_STATUS_COMPARE_DE",
		"ANIM618_FINGERPRINT_STATUS_COMPLETE_DE",
		/* file 199 */
		"ANIM619_FINGERPRINT_STATUS_COMPARE_ES",
		"ANIM620_FINGERPRINT_STATUS_COMPLETE_ES",
		/* file 200 */
		"ANIM621_CASE5_INTRO_WINDOW_FLYBY",
		/* file 201 */
		"ANIM622_CASE5_INTRO_SKYSCRAPER",
		/* file 202 */
		"ANIM623_CASE5_INTRO_CLOUDS_LIGHTING",
		/* file 203 */
		"ANIM624_CASE5_INTRO_STABFX",
		/* file 204 */
		"ANIM625_CASE5_INTRO_LANA_STABHAND",
		/* file 205 */
		"ANIM626_UNK_BLANK1",
		/* file 206 */
		"ANIM627_CASE5_INTRO_LANA_UPPERHEAD",
		/* file 207 */
		"ANIM628_CASE5_INTRO_LANA_LOWERHEAD",
		/* file 208 */
		"ANIM629_CASE5_INTRO_LANA_UPPERBODY",
		/* file 209 */
		"ANIM630_CASE5_INTRO_LANA_MIDBODY",
		/* file 210 */
		"ANIM631_CASE5_INTRO_LANA_LOWERBODY",
		/* file 211 */
		"ANIM632_CASE5_INTRO_KNIFESPIN",
		/* file 212 */
		"ANIM633_OVERLAY_MARSHALL_SHAVE_SHAVING",
		"ANIM634_OVERLAY_MARSHALL_SHAVE_IDLE",
		"ANIM635_OVERLAY_MARSHALL_SHAVE_TALKING",
		/* file 213 */
		"ANIM636_OVERLAY_MARSHALL_DRINK_IDLE1",
		"ANIM637_OVERLAY_MARSHALL_DRINK_IDLE2",
		"ANIM638_OVERLAY_MARSHALL_DRINK_DRINKING",
		"ANIM639_OVERLAY_MARSHALL_DRINK_ENDDRINKING",
		/* file 214 */
		"ANIM640_OVERLAY_MARSHALL_ANXIOUS_RIPOFF",
		"ANIM641_OVERLAY_MARSHALL_ANXIOUS_IDLE",
		"ANIM642_OVERLAY_MARSHALL_ANXIOUS_STATIC"
		"ANIM643_OVERLAY_MARSHALL_ANXIOUS_TALKING"
		/* file 215 */
		"ANIM644_UNKNOWN_BLADE",
		/* file 216 */
		"ANIM645_CASE5_INTRO_RAIN",
		/* file 217 */
		"ANIM646_UNK_BLANK2",
		/* file 218 */
		"ANIM647_UNK_BLANK3",
		/* file 219 */
		"ANIM648_UNK_BLANK4",
		/* file 220 */
		"ANIM649_UNK_BLANK5",
		/* file 221 */
		"ANIM650_UNK_BLANK6",
		/* file 222 */
		"ANIM651_UNK_BLANK7",
		/* file 223 */
		"ANIM652_UNK_BLANK8",
		/* file 224 */
		"ANIM653_UNK_BLANK9",
		/* file 225 */
		"ANIM654_UNK_BLANK10",
		/* file 226 */
		"ANIM655_UNK_BLANK11",
		/* file 227 */
		"ANIM656_UNK_BLANK12",
		/* file 228 */
		"ANIM657_UNK_BLANK13",
		/* file 229 */
		"ANIM658_UNK_GREEN_LIGHT",
		/* file 230 */
		"ANIM659_UNK_RED_LIGHT",
		/* file 231 */
		"ANIM660_UNK_BLACK_EDGE",
		/* file 232 */
		"ANIM661_SAFE_PROMPT_JP"
		/* file 233 */
		"ANIM662_SAFE_ENTRY_GOOD"
		/* file 234 */
		"ANIM663_SAFE_ENTRY_BAD_JP",
		/* file 235 */
		"ANIM664_CASE5_GARAGE_VIEWCONE_LEFTRIGHT",
		/* file 236 */
		"ANIM665_CASE5_GARAGE_LUMINOL_MARKER",
		/* file 237 */
		"ANIM666_LUNCHBOX01",
		/* file 238 */
		"ANIM667_LUNCHBOX02",
		/* file 239 */
		"ANIM668_LUNCHBOX03",
		/* file 240 */
		"ANIM669_LUNCHBOX04",
		/* file 241 */
		"ANIM670_LUNCHBOX05",
		/* file 242 */
		"ANIM671_LUNCHBOX06",
		/* file 243 */
		"ANIM672_LUNCHBOX07",
		/* file 244 */
		"ANIM673_LUNCHBOX08",
		/* file 245 */
		"ANIM674_LUNCHBOX09",
		/* file 246 */
		"ANIM675_LUNCHBOX10",
		/* file 247 */
		"ANIM676_LUNCHBOX11",
		/* file 248 */
		"ANIM677_LUNCHBOX12_PACKAGE",
		/* file 249 */
		"ANIM678_LUNCHBOX13",
		/* file 250 */
		"ANIM679_LUNCHBOX14",
		/* file 251 */
		"ANIM680_LUNCHBOX15",
		/* file 252 */
		"ANIM681_LUNCHBOX16",
		/* file 253 */
		"ANIM682_LUNCHBOX17",
		/* file 254 */
		"ANIM683_LUNCHBOX18_PACKAGE2",
		/* file 255 */
		"ANIM684_LUNCHBOX19_PACKAGE3",
		/* file 256 */
		"ANIM685_LUNCHBOX20",
		/* file 257 */
		"ANIM686_LUNCHBOX21",
		/* file 258 */
		"ANIM687_GAVEL_SLAM_SINGLE",
		"ANIM688_GAVEL_SLAM_MULTI",
		/* file 259 */
		"ANIM689_COURT_WIDEANGLE_DEFENSE_PHOENIX",
		/* file 260 */
		"ANIM690_COURT_WIDEANGLE_DEFENSE_MIA",
		/* file 261 */
		"ANIM691_COURT_WIDEANGLE_PROSECUTION_PAYNE",
		/* file 262 */
		"ANIM692_COURT_WIDEANGLE_BUTZ",
		/* file 263 */
		"ANIM693_COURT_WIDEANGLE_SAHWIT",
		/* file 264 */
		"ANIM694_COURT_WIDEANGLE_AUDIENCE_RIGHT1",
		"ANIM695_COURT_WIDEANGLE_AUDIENCE_RIGHT2",
		/* file 265 */
		"ANIM696_COURT_WIDEANGLE_WHITE",
		/* file 266 */
		"ANIM697_COURT_WIDEANGLE_MAY",
		/* file 267 */
		"ANIM698_COURT_WIDEANGLE_GUMSHOE",
		/* file 268 */
		"ANIM699_COURT_WIDEANGLE_PROSECUTION_EDGEWORTH",
		/* file 269 */
		"ANIM700_COURT_WIDEANGLE_DEFENSE_SUMMONED_MIA",
		/* file 270 */
		"ANIM701_COURT_WIDEANGLE_DEFENSE_MAYA",
		/* file 271 */
		"ANIM702_COURT_WIDEANGLE_OLDBAG",
		/* file 272 */
		"ANIM703_COURT_WIDEANGLE_HACKINS",
		/* file 273 */
		"ANIM704_COURT_WIDEANGLE_MANELLA",
		/* file 274 */
		"ANIM705_COURT_WIDEANGLE_VASQUEZ",
		/* file 275 */
		"ANIM706_COURT_WIDEANGLE_JUDGE",
		/* file 276 */
		"ANIM707_COURT_WIDEANGLE_HART",
		/* file 277 */
		"ANIM708_COURT_WIDEANGLE_OLDMAN",
		/* file 278 */
		"ANIM709_COURT_WIDEANGLE_EDGEWORTH",
		/* file 279 */
		"ANIM710_COURT_WIDEANGLE_PROSECUTION_VONKARMA",
		/* file 280 */
		"ANIM711_COURT_WIDEANGLE_MAYA",
		/* file 281 */
		"ANIM712_COURT_WIDEANGLE_POWERS",
		/* file 282 */
		"ANIM713_COURT_WIDEANGLE_MEEKINS",
		/* file 283 */
		"ANIM714_COURT_WIDEANGLE_EMA",
		/* file 284 */
		"ANIM715_COURT_WIDEANGLE_DEFENSE_EMA",
		/* file 285 */
		"ANIM710_COURT_WIDEANGLE_LANA",
		/* file 286 */
		"ANIM710_COURT_WIDEANGLE_MARSHALL",
		/* file 287 */
		"ANIM710_COURT_WIDEANGLE_STARR",
		/* file 288 */
		"ANIM710_COURT_WIDEANGLE_GANT",
	},
	/* phoenix 2 */
	{
		0
	},
	/* phoenix 3 */
	{
		0
	},
	/* apollo */
	{
		0
	},
};

/* 1024 is a placeholder, change when all things are known */
char *sound_data[4][1024] = {
	{
		/* phoenix 1 */
		/* BEGIN BGM */
		"BGM000_DETENTION_CENTER",
		"BGM001_GUMSHOES_THEME",
		"BGM002_CORNERED",
		"BGM003_CORNERED_VARIATION",
		"BGM004_OBJECTION",
		"BGM005_LOGIC_AND_TRICK",
		"BGM006_MAYAS_THEME",
		"BGM007_ENDING",
		"BGM008_COURTROOM_LOBBY",
		"BGM009_UNUSED",
		"BGM010_QUESTIONING_MODERATO",
		"BGM011_QUESTIONING_ALLEGRO",
		"BGM012_INVESTIGATION_CORE",
		"BGM013_COURTROOM_OPENING",
		"BGM014_JINGLE_SURPRISE",
		"BGM015_JINGLE_EVIDENCE",
		"BGM016_JINGLE_SAVE",
		"BGM017_JINGLE_IDEA",
		"BGM018_SUSPENSE",
		"BGM019_TURNABOUT_SISTERS_BALLAD", 
		"BGM020_VICTORY",
		"BGM021_STEEL_SAMURAI_THEME",
		"BGM022_HAPPY_PEOPLE",
		"BGM023_INTRO_CASE_1",
		"BGM024_TELLING_THE_TRUTH",
		"BGM025_INVESTIGATION_OPENING",
		"BGM026_GROSSBERGS_THEME",
		"BGM027_RECOLLECTION_DL_6",
		"BGM028_RECOLLECTION_MAYA",
		"BGM029_RECOLLECTION_CLASS_TRIAL",
		"BGM030_RECOLLECTION_STUDIO",
		"BGM031_AMBIENT_BIRD_CHIRPS",
		"BGM032_JINGLE_WRONG_CHOICE",
		"BGM033_UNKNOWN",
		"BGM034_UNKNOWN",
		"BGM035_UNKNOWN",
		"BGM036_UNKNOWN",
		"BGM037_UNKNOWN",
		"BGM038_UNKNOWN",
		"BGM039_UNKNOWN",
		"BGM040_UNKNOWN",
		"BGM041_UNKNOWN",
		/* END BGM */
		/* BEGIN SE */
		"SE000_MENU_CHANGE",
		"SE001_MENU_CONFIRM",
		"SE002_MENU_CANCEL",
		"SE003_TEXT_BLIP_MALE",
		"SE004_TEXT_BLIP_FEMALE",
		"SE005_TEXT_ADVANCE",
		"SE006_TEXT_BLIP_TYPEWRITER_HIGH",
		"SE007_MENU_OPEN_SUBMENU",
		0,
		"SE009_DISPLAY_EVIDENCE",
		"SE00A_UNKNOWN",
		"SE00B_UNKNOWN",
		"SE00C_MENU_CHANGE_PAGE",
		"SE00D_VOICE_PHOENIX_TAKE_THAT_JP",
		"SE00E_VOICE_EDGEWORTH_OBJECTION_JP",
		"SE00F_VOICE_PAYNE_OBJECTION_JP",
		"SE010_GAVEL_SLAM",
		"SE011_GAVEL_SLAM_TRIPLE",
		"SE012_GAVEL_SLAM_HEXA",
		"SE013_COURTROOM_AUDIENCE_1",
		"SE014_COURTROOM_AUDIENCE_2",
		"SE015_COURTROOM_AUDIENCE_UPROAR",
		"SE016_CONFIRM_SAVE",
		"SE017_VOICE_VON_KARMA_OBJECTION_JP",
		"SE018_PHOTO_SNAPSHOT",
		"SE019_IMPACT",
		"SE01A_TEXT_TYPEWRITER_LOW",
		"SE01B_CRASH",
		"SE01C_DESK_HIT",
		"SE01D_VOICE_PHOENIX_HOLD_IT_JP",
		"SE01E_EXCLAMATION",
		"SE01F_POLICE_SIREN",
		"SE020_DOOR_OPEN_IMPACT",
		"SE021_COLLAPSE_IMPACT",
		"SE022_LOST_A_TRY",
		"SE023_TYPEWRITER_LOW",
		"SE024_CRITICAL_HIT",
		"SE025_GUNSHOT_1",
		"SE026_VERBAL_HIT",
		"SE027_VOICE_PHOENIX_OBJECTION_JP",
		"SE028_CRASH_INTO_WATER",
		"SE029_BEGIN_QUESTIONING",
		"SE02A_TEXT_TYPEWRITER_LOW",
		"SE02B_TEXT_TYPEWRITER_HIGH",
		"SE02C_GAME_OVER",
		"SE02D_UNEXPECTED_TURN_OF_EVENTS",
		"SE02E_UNKNOWN",
		"SE02F_UNKNOWN",
		"SE030_PHONE_RING",
		"SE031_PHONE_PICKUP",
		"SE032_PHONE_END_OF_RECORDING",
		"SE033_CAMERA_SOUND_ZOOM_IN",
		"SE034_DOG_BARK",
		"SE035_VON_KARMA_SNAP",
		"SE036_JAPANESE_WOOD_SOUND",
		"SE037_UNKNOWN_EARTHQUAKE",
		"SE038_JAPANESE_HIT",
		"SE039_STICK_SNAP",
		"SE03A_ELECTRO_SHOCK",
		"SE03B_FIRE_ALARM",
		"SE03C_COURTROOM_AUDIENCE_VICTORY",
		"SE03D_UNKNOWN",
		"SE03E_REDD_BLING_SPARKLES",
		"SE03F_CRASH_THROUGH_DOOR",
		0,
		"SE041_PHONE_RINGTONE_STEEL_SAMURAI",
		0,
		"SE043_UNKNOWN",
		
		[121] = "SE04F_SWOOSH",
		"SE050_SHOCKING_TURN_OF_EVENTS",
		
		[157] = "SE073_STOMACH_GRUMBLE",
		
		/* this seems to be a thing */
		[255] = "BGMSP_RESUMEPLAYING",
		
		[380] = "BGM150_EMAS_THEME",
		"BGM151_MARSHALLS_THEME",
		"BGM152_RECOLLECTION_SL_9",
		"BGM153_GANTS_THEME",
		"BGM154_INTRO_CASE_5",
		"BGM155_ENDING_CASE_5",
		"BGM156_BLUE_BADGERS_THEME",
		
		[400] = "SE0B0_VOICE_PHOENIX_OBJECTION_EN",
		"SE0B1_VOICE_PHOENIX_HOLD_IT_EN",
		"SE0B2_VOICE_PAYNE_OBJECTION_EN",
		"SE0B3_VOICE_EDGEWORTH_OBJECTION_EN",
		"SE0B4_VOICE_VON_KARMA_OBJECTION_EN",
		"SE0B5_VOICE_PHOENIX_TAKE_THAT_EN",
		"SE0B6_COURTROOM_AUDIENCE_3",
		"SE0B7_SLAP",
		"SE0B8_GUNSHOT_2",
		"SE0B9_THUNDER",
		"SE0BA_METAL_CLANG",
		"SE0BB_ORGAN",
		"SE0BC_LOCK_OPEN_LIGHTSWITCH",
		"SE0BD_ELECTRONIC_INTERACTION",
		"SE0BE_ELECTRONIC_CONFIRMATION",
		"SE0BF_ELECTRONIC_ENTRY",
		"SE0C0_FINGERPRINT_MATCH",
		"SE0C1_ELECTROMECHANIC_ENTRY",
		"SE0C2_MEEKINS_LOUDSPEAKER",
		"SE0C3_UNKNOWN",
		"SE0C4_FINGERPRINT_DUSTING",
		"SE0C5_OPEN",
		"SE0C6_FINGERPRINT_CHECKING",
		"SE0C7_FINGERPRINT_POINT",
		"SE0C8_VIDEOPLAYER_PLAYPAUSE",
		"SE0C9_VIDEOPLAYER_SEEK",
		"SE0CA_VIDEOPLAYER_STEP_1",
		"SE0CB_VIDEOPLAYER_STEP_2",
		"SE0CC_VASE_PUZZLE_MATCH_1",
		"SE0CD_VASE_PUZZLE_MATCH_2",
		"SE0CE_SAFE_PANEL_SOUND_1",
		"SE0CF_SAFE_PANEL_SOUND_2",
		"SE0D0_SAFE_PANEL_SOUND_3",
		"SE0D1_SAFE_PANEL_SOUND_4",
		"SE0D2_SAFE_PANEL_SOUND_5",
		"SE0D3_SAFE_PANEL_SOUND_6",
		"SE0D4_CASE_5_INTRO_WINDOW_SWOOSH",
		"SE0D5_CASE_5_INTRO_RAIN_1",
		"SE0D6_CASE_5_INTRO_THUNDER_1",
		0,
		"SE0D8_CASE_5_INTRO_LIGHTNING_1",
		"SE0D9_CASE_5_INTRO_LIGHTNING_2",
		"SE0DA_CASE_5_INTRO_LIGHTNING_3",
		"SE0DB_CASE_5_INTRO_THUNDER_2",
		"SE0DC_CASE_5_INTRO_RAIN_2",
		"SE0DD_CASE_5_INTRO_THUNDER_3",
		"SE0DE_CASE_5_INTRO_SWING",
		"SE0DF_CASE_5_INTRO_FLYING_OBJECT",
		"SE0E0_CASE_5_INTRO_SHATTER",
		"SE0E1_CASE_5_INTRO_SHOCK",
		"SE0E2_CASE_5_INTRO_THUNDER_4",
		"SE0E3_UNKNOWN",
		"SE0E5_UNKNOWN",
		"SE0E4_GUNSHOT_3",
		"SE0E6_BOTTLE_OPEN",
		"SE0E7_GAVEL_SLAM_2",
		"SE0E8_MEEKINS_LOUDSPEAKER_SQUEAK",
		0,
		"SE0EA_VOICE_PHOENIX_OBJECTION_FR",
		"SE0EB_VOICE_PHOENIX_HOLD_IT_FR",
		"SE0EC_VOICE_PAYNE_OBJECTION_FR",
		"SE0ED_VOICE_EDGEWORTH_OBJECTION_FR",
		"SE0EE_VOICE_VON_KARMA_OBJECTION_FR",
		"SE0EF_VOICE_PHOENIX_TAKE_THAT_FR",
		"SE0F0_VOICE_PHOENIX_OBJECTION_IT",
		"SE0F1_VOICE_PHOENIX_HOLD_IT_IT",
		"SE0F2_VOICE_PHOENIX_TAKE_THAT_IT",
		"SE0F3_VOICE_PAYNE_OBJECTION_IT",
		"SE0F4_VOICE_EDGEWORTH_OBJECTION_IT",
		"SE0F5_VOICE_VON_KARMA_OBJECTION_IT",
		"SE0F6_VOICE_PHOENIX_OBJECTION_DE",
		"SE0F7_VOICE_PHOENIX_HOLD_IT_DE",
		"SE0F8_VOICE_PHOENIX_TAKE_THAT_DE",
		"SE0F9_VOICE_PAYNE_OBJECTION_DE",
		"SE0FA_VOICE_EDGEWORTH_OBJECTION_DE",
		"SE0FB_VOICE_VON_KARMA_OBJECTION_DE",
		"SE0FC_VOICE_PHOENIX_OBJECTION_ES",
		"SE0FD_VOICE_PHOENIX_HOLD_IT_ES",
		"SE0FE_VOICE_PHOENIX_TAKE_THAT_ES",
		"SE0FF_VOICE_PAYNE_OBJECTION_ES",
		"SE100_VOICE_EDGEWORTH_OBJECTION_ES",
		"SE101_VOICE_VON_KARMA_OBJECTION_ES",
		/*_this_table_lacks_various_clips_from_the_euro_version
		such_as_IT, ES_and_DE_voiceclips */
	},
	{
		/* phoenix 2 */
		/* everything up to BGM041 is from phoenix 1 */
		
		[1] = "BGM001_GUMSHOES_THEME",
		"BGM002_CORNERED_1",
		
		[6] = "BGM006_MAYAS_THEME",
		"BGM007_ENDING",
		0,
		"BGM009_UNUSED",
		0, 0,
		"BGM012_INVESTIGATION_CORE_1",
		0,
		"BGM014_JINGLE_SURPRISE",
		"BGM015_JINGLE_EVIDENCE",
		"BGM016_JINGLE_SAVE",
		"BGM017_JINGLE_IDEA",
		"BGM018_SUSPENSE_1",
		"BGM019_TURNABOUT_SISTERS_BALLAD_1",
		0,
		"BGM021_STEEL_SAMURAI_THEME",
		"BGM022_HAPPY_PEOPLE",
		"BGM023_INTRO_CASE_1",
		0,
		"BGM025_INVESTIGATION_OPENING_1",
		"BGM026_GROSSBERGS_THEME",
		"BGM027_RECOLLECTION_DL_6",
		"BGM028_RECOLLECTION_MAYA",
		"BGM029_RECOLLECTION_CLASS_TRIAL",
		"BGM030_RECOLLECTION_STUDIO",
		"BGM031_AMBIENT_BIRD_CHIRPS",
		"BGM032_JINGLE_WRONG_CHOICE",
		"BGM033_UNKNOWN",
		"BGM034_UNKNOWN",
		"BGM035_UNKNOWN",
		"BGM036_UNKNOWN",
		"BGM037_UNKNOWN",
		"BGM038_UNKNOWN",
		"BGM039_UNKNOWN",
		"BGM040_UNKNOWN",
		"BGM041_UNKNOWN",
		
		
		
		"SE000_MENU_CHANGE",
		"SE001_MENU_CONFIRM",
		"SE002_MENU_CANCEL",
		"SE003_TEXT_BLIP_MALE",
		"SE004_TEXT_BLIP_FEMALE",
		"SE005_TEXT_ADVANCE",
		0,
		"SE007_MENU_OPEN_SUBMENU",
		0,
		"SE009_DISPLAY_EVIDENCE",
		"SE00A_UNKNOWN",
		0,
		"SE00C_MENU_CHANGE_PAGE",
		"SE00D_VOICE_PHOENIX_TAKE_THAT_JP",
		"SE00E_VOICE_EDGEWORTH_OBJECTION_JP",
		"SE00F_VOICE_PAYNE_OBJECTION_JP",
		"SE010_GAVEL_SLAM",
		"SE011_GAVEL_SLAM_TRIPLE",
		0,
		"SE013_COURTROOM_AUDIENCE_1",
		0,
		0,
		"SE016_CONFIRM_SAVE",
		0,
		0,
		"SE019_IMPACT",
		"SE01A_TEXT_TYPEWRITER_LOW",
		0,
		"SE01C_DESK_HIT",
		"SE01D_VOICE_PHOENIX_HOLD_IT_JP",
		"SE01E_EXCLAMATION",
		0,
		"SE020_DOOR_OPEN_IMPACT",
		"SE021_COLLAPSE_IMPACT",
		"SE022_LOST_A_TRY",
		0,
		"SE024_CRITICAL_HIT",
		"SE025_GUNSHOT_1",
		"SE026_VERBAL_HIT",
		"SE027_VOICE_PHOENIX_OBJECTION_JP",
		0,
		"SE029_BEGIN_QUESTIONING",
		0,
		0,
		"SE02C_GAME_OVER",
		"SE02D_UNEXPECTED_TURN_OF_EVENTS",
		0,
		0,
		0,
		0,
		0,
		"SE033_CAMERA_SOUND_ZOOM_IN",
		"SE034_DOG_BARK",
		"SE035_VON_KARMA_SNAP",
		"SE036_JAPANESE_WOOD_SOUND",
		"SE037_UNKNOWN_EARTHQUAKE",
		"SE038_JAPANESE_HIT",
		"SE039_STICK_SNAP",
		"SE03A_ELECTRO_SHOCK",
		"SE03B_FIRE_ALARM",
		"SE03C_COURTROOM_AUDIENCE_VICTORY",
		"SE03D_UNKNOWN",
		"SE03E_REDD_BLING_SPARKLES",
		"SE03F_CRASH_THROUGH_DOOR",
		"SE040_PHONE_RINGTONE_WELLINGTON",
		"SE041_PHONE_RINGTONE_STEEL_SAMURAI",
		"SE042_SHORT_BEEP",
		"SE043_UNKNOWN",
		"SE044_UNKNOWN",
		"SE045_GAVEL_SLAM_REVERB",
		"SE046_WHIP",
		0,
		0,
		"SE049_PSYCHE_LOCK_SLAM",
		"SE04A_PSYCHE_LOCK_BREAK",
		"SE04B_CAR_CRASH",
		"SE04C_UNKNOWN_DOOR_OPEN",
		"SE04D_WOOD_DOOR_IMPACT",
		0,
		"SE04F_SWOOSH",
		"SE050_SHOCKING_TURN_OF_EVENTS",
		"SE051_LION_ROAR",
		"SE052_MONKEY_SCREECH",
		"SE053_SPOT_LIGHT_ON",
		"SE054_UNKNOWN_AHA",
		"SE055_WOOD_DOOR_BREAKDOWN",
		"SE056_PHYCHE_LOCK_CHAINS_1",
		"SE057_PHYCHE_LOCK_CHAINS_2",
		"SE058_PHYCHE_LOCK_CHAINS_3",
		"SE059_PHYCHE_LOCK_CHAINS_4",
		"SE05A_PHYCHE_LOCK_CHAINS_5",
		"SE05B_CAR_ENGINE",
		"SE05C_CAR_SWOOP_LEFTRIGHT",
		"SE05D_CAR_SWOOP_RIGHTLEFT",
		"SE05E_CAR_ENGINE_CRESCENDO",
		"SE05F_CIRCUS_DRUMROLL",
		"SE060_CIRCUS_DRUM",
		"SE061_UNKNOWN_CIRCUS_SE",
		"SE062_LOW_AUDIENCE_CHEERS",
		"SE063_HIGH_AUDIENCE_CHEERS_LONG",
		"SE064_CIRCUS_WHIP",
		"SE065_LONG_LION_ROAR",
		"SE066_HIGH_AUDIENCE_CHEERS_SHORT",
		"SE067_OLDBAG_LAZERBLASTER",
		"SE068_RADIO_TRANSMITTER_RINGTONE",
		"SE069_RADIO_TRANSMITTER_PICKUP",
		"SE06A_RADIO_TRANSMITTER_END",
		"SE06B_RADIO_TRANSMITTER_INTERFERENCE",
		"SE06C_VOICE_FRANZISKA_OBJECTION_JP",
		"SE06D_PHONE_CALLER_QUIT",
		"SE06E_FRANZISKAS_TRACKER?",
		"SE06F_UNKNOWN",
		"SE070_DOOR_UNLOCK",
		"SE071_CAT_MEOW",
		"SE072_LIFE_BAR_RESTORE",
		"SE073_STOMACH_GROWL",
		"SE074_PHONE_DIAL_1",
		"SE075_PHONE_DIAL_2",
		"SE076_PHONE_DIAL_3",
		"SE077_PHONE_DIAL_4",
		"SE078_PHONE_DIAL_5",
		"SE079_COURTROOM_AUDIENCE_2",
		"SE07A_COURTROOM_AUDIENCE_3",
		"SE07B_COURTROOM_AUDIENCE_FADE",
		"SE07C_COURTROOM_HEADLINE_IN",
		"SE07D_COURTROOM_HEADLINE_OUT",
		0,
		"SE07F_UNKNOWN_AHA?",
		"SE080_UNKNOWN_GROWL",
		"SE081_HIGH_AUDIENCE_CHEER_LOOP",
		"SE082_RADIO_DETECTOR_LOW",
		"SE083_PHONE_DIALLING",
		"SE084_RADIO_DETECTOR_MEDIUM",
		"SE085_UNKNOWN_SLAM",
		"SE086_PSYCHE_LOCK_BREAK_2?",
		
		[201] = "BGM051_INTRO_CASE_1_PART_1",
		"BGM052_INTRO_CASE_3_AND_4",
		"BGM053_STEEL_SAMURAIS_BALLAD",
		"BGM054_TURNABOUT_SISTERS_THEME_2",
		"BGM055_BERRY_BIG_CIRCUS",
		0,
		"BGM057_KURAIN_VILLAGE",
		"BGM058_DETENTION_CENTER",
		"BGM059_ECCENTRIC",
		0,
		"BGM061_SHELLY_DE_KILLER_THEME",
		"BGM062_RECOLLECTION_FEYS",
		"BGM063_RECOLLECTION_ANDREWS",
		"BGM064_INVESTIGATION_CORE_2",
		"BGM065_INVESTIGATION_OPENING_2",
		0,
		"BGM067_EDGEWORTHS_THEME",
		"BGM068_ANNOYING_PEOPLE_MOE_OLDBAG",
		"BGM069_COURTROOM_OPENING_2",
		"BGM070_OBJECTION_2",
		"BGM071_TRICK_AND_MAGIC",
		"BGM072_QUESTIONING_MODERATO_2",
		"BGM073_QUESTIONING_ALLEGRO_2",
		"BGM074_CORNERED_2",
		"BGM075_CORNERED_2_VARIATION",
		"BGM076_VICTORY_2",
		"BGM077_COURTROOM_LOBBY_2",
		"BGM078_TELLING_THE_TRUTH_2",
		0,
		"BGM080_JINGLE_SAVE_2",
		0,
		0,
		"BGM083_ENDING_2_PART_1",
		"BGM084_INTRO_CASE_1_PART_2",
		"BGM085_PSYCHE_LOCK_2",
		"BGM086_HOTLINE_OF_FATE",
		"BGM087_FRANZISKAS_THEME",
		"BGM088_INVESTIGATION_MIDDLE_2",
		"BGM089_EDGEWORTH_OUTRO",
		"BGM090_AUDIENCE_BGM?",
		"BGM091_FRANZISKAS_THEME_VARIATION",
		"BGM092_PEARLS_THEME",
		"BGM093_ENDING_2_PART_1_VARIATION",
		"BGM094_ENDING_2_PART_2",
		
		/* this seems to be a thing */
		[256] = "BGMSP_RESUMEPLAYING",
		
		[400] = "SE0B0_VOICE_PHOENIX_OBJECTION_EN",
		"SE0B1_VOICE_PHOENIX_HOLD_IT_EN",
		"SE0B2_VOICE_PAYNE_OBJECTION_EN",
		"SE0B3_VOICE_EDGEWORTH_OBJECTION_EN",
		0,
		"SE0B5_VOICE_PHOENIX_TAKE_THAT_EN",
		"SE0B6_VOICE_FRANZISKA_OBJECTION_EN",
		0,
		"SE0B8_VOICE_FRANZISKA_OBJECTION_FR",
		0,
		0,
		0,
		"SE0BC_VOICE_FRANZISKA_OBJECTION_DE",
		0,
		0,
		"SE0BF_VOICE_FRANZISKA_OBJECTION_IT",
		0,
		0,
		0,
		"SE0C3_VOICE_FRANZISKA_OBJECTION_ES",
		"SE0EA_VOICE_PHOENIX_OBJECTION_FR",
		"SE0EB_VOICE_PHOENIX_HOLD_IT_FR",
		"SE0EF_VOICE_PHOENIX_TAKE_THAT_FR",
		"SE0EC_VOICE_PAYNE_OBJECTION_FR",
		"SE0ED_VOICE_EDGEWORTH_OBJECTION_FR",
		"SE0F0_VOICE_PHOENIX_OBJECTION_IT",
		"SE0F1_VOICE_PHOENIX_HOLD_IT_IT",
		"SE0F2_VOICE_PHOENIX_TAKE_THAT_IT",
		"SE0F3_VOICE_PAYNE_OBJECTION_IT",
		"SE0F4_VOICE_EDGEWORTH_OBJECTION_IT",
		"SE0F6_VOICE_PHOENIX_OBJECTION_DE",
		"SE0F7_VOICE_PHOENIX_HOLD_IT_DE",
		"SE0F8_VOICE_PHOENIX_TAKE_THAT_DE",
		"SE0F9_VOICE_PAYNE_OBJECTION_DE",
		"SE0FA_VOICE_EDGEWORTH_OBJECTION_DE",
		"SE0FC_VOICE_PHOENIX_OBJECTION_ES",
		"SE0FD_VOICE_PHOENIX_HOLD_IT_ES",
		"SE0FE_VOICE_PHOENIX_TAKE_THAT_ES",
		"SE0FF_VOICE_PAYNE_OBJECTION_ES",
		"SE100_VOICE_EDGEWORTH_OBJECTION_ES",
	},
	{
		/* phoenix 3 to be done */
		/* everything up to BGM041 is from phoenix 1 */
		
		[1] = "BGM001_GUMSHOES_THEME",
		"BGM002_CORNERED_1",
		"BGM003_CORNERED_1_VARIATION",
		
		[12] = "BGM012_INVESTIGATION_CORE_1",
		0,
		"BGM014_JINGLE_SURPRISE",
		"BGM015_JINGLE_EVIDENCE",
		0,
		0,
		"BGM018_SUSPENSE_1",
		"BGM019_TURNABOUT_SISTERS_BALLAD_1",
		0,
		0,
		"BGM022_HAPPY_PEOPLE",
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		"BGM031_AMBIENT_BIRD_CHIRPS_1",
		
		[42] = "SE000_MENU_CHANGE",
		"SE001_MENU_CONFIRM",
		"SE002_MENU_CANCEL",
		"SE003_TEXT_BLIP_MALE",
		"SE004_TEXT_BLIP_FEMALE",
		"SE005_TEXT_ADVANCE",
		0,
		"SE007_MENU_OPEN_SUBMENU",
		0,
		"SE009_DISPLAY_EVIDENCE",
		"SE00A_UNKNOWN",
		0,
		"SE00C_MENU_CHANGE_PAGE",
		"SE00D_VOICE_PHOENIX_TAKE_THAT_FR",
		"SE00E_VOICE_EDGEWORTH_OBJECTION_FR",
		"SE00F_VOICE_PAYNE_OBJECTION_FR",
		"SE010_GAVEL_SLAM",
		"SE011_GAVEL_SLAM_TRIPLE",
		0,
		"SE013_COURTROOM_AUDIENCE_1",
		0,
		0,
		"SE016_CONFIRM_SAVE",
		0,
		0,
		"SE019_IMPACT",
		"SE01A_TEXT_TYPEWRITER_LOW",
		0,
		"SE01C_DESK_HIT",
		"SE01D_VOICE_PHOENIX_HOLD_IT_FR",
		"SE01E_EXCLAMATION",
		0,
		"SE020_DOOR_OPEN_IMPACT",
		"SE021_COLLAPSE_IMPACT",
		"SE022_LOST_A_TRY",
		0,
		"SE024_CRITICAL_HIT",
		"SE025_GUNSHOT_1",
		"SE026_VERBAL_HIT",
		"SE027_VOICE_PHOENIX_OBJECTION_FR",
		"SE028_CRASH_INTO_WATER",
		"SE029_BEGIN_QUESTIONING",
		0,
		0,
		"SE02C_GAME_OVER",
		"SE02D_UNEXPECTED_TURN_OF_EVENTS",
		0,
		0,
		"SE030_PHONE_RING",
		"SE031_PHONE_PICKUP",
		0,
		"SE033_CAMERA_SOUND_ZOOM_IN",
		0,
		"SE035_VON_KARMA_SNAP",
		
		[102] = "SE03C_COURTROOM_AUDIENCE_VICTORY",
		
		[107] = "SE041_PHONE_RINGTONE_STEEL_SAMURAI",
		"SE042_SHORT_BEEP",
		0,
		"SE044_UNKNOWN",
		"SE045_GAVEL_SLAM_REVERB",
		"SE046_WHIP",
		0,
		0,
		"SE049_PSYCHE_LOCK_SLAM",
		"SE04A_PSYCHE_LOCK_BREAK",
		0,
		"SE04C_UNKNOWN_DOOR_OPEN",
		0,
		0,
		"SE04F_SWOOSH",
		"SE050_SHOCKING_TURN_OF_EVENTS",
		"SE051_LION_ROAR",
		0,
		"SE053_SPOT_LIGHT_ON",
		"SE054_UNKNOWN_AHA",
		0,
		"SE056_PHYCHE_LOCK_CHAINS_1",
		"SE057_PHYCHE_LOCK_CHAINS_2",
		"SE058_PHYCHE_LOCK_CHAINS_3",
		"SE059_PHYCHE_LOCK_CHAINS_4",
		"SE05A_PHYCHE_LOCK_CHAINS_5",
		
		[145] = "SE067_OLDBAG_LAZERBLASTER",
		
		[150] = "SE06C_VOICE_FRANZISKA_OBJECTION_FR",
		0,
		0,
		"SE06F_UNKNOWN",
		"SE070_DOOR_UNLOCK",
		0,
		"SE072_LIFE_BAR_RESTORE",
		"SE073_STOMACH_GROWL",
		
		[163] = "SE079_COURTROOM_AUDIENCE_2",
		"SE07A_COURTROOM_AUDIENCE_3",
		"SE07B_COURTROOM_AUDIENCE_FADE",
		"SE07C_COURTROOM_HEADLINE_IN",
		"SE07D_COURTROOM_HEADLINE_OUT",
		0,
		0,
		0,
		0,
		"SE082_RADIO_DETECTOR_LOW",
		0,
		"SE084_RADIO_DETECTOR_MEDIUM",
		"SE085_UNKNOWN_SLAM",
		0,
		0,
		"SE088_COFFE_GULP",
		"SE089_COFFE_SWOOP",
		"SE08A_UNKNOWN_CLAP?",
		"SE08B_COFFE_GULP_MARATHON_2",
		"SE08C_COFFE_GULP_MARATHON_3",
		"SE08D_COFFE_GULP_MARATHON_4",
		
		[203] = "BGM053_STEEL_SAMURAIS_BALLAD",
		"BGM054_TURNABOUT_SISTERS_THEME_2",
		0,
		0,
		"BGM057_KURAIN_VILLAGE",
		"BGM058_DETENTION_CENTER",
		"BGM059_ECCENTRIC",
		"BGM060_AMBIENT_BIRD_CHIRPS_3",
		0,
		0,
		0,
		"BGM064_INVESTIGATION_CORE_2",
		0,
		"BGM066_SUSPENSE_1",
		0,
		0,
		0,
		0,
		"BGM071_TRICK_AND_MAGIC",
		0,
		0,
		0,
		0,
		0,
		"BGM077_COURTROOM_LOBBY_2",
		0,
		"BGM079_PSYCHE_LOCK_3",
		0,
		"BGM081_JINGLE_EVIDENCE_1",
		"BGM082_FRANZISKAS_THEME_3",
		0,
		0,
		"BGM085_PSYCHE_LOCK_2",
		"BGM086_HOTLINE_OF_FATE",
		"BGM087_FRANZISKAS_THEME_2",
		0,
		0,
		"BGM090_AUDIENCE_BGM?",
		0,
		"BGM092_PEARLS_THEME",
		
		/* this seems to be a thing */
		[256] = "BGMSP_RESUMEPLAYING",
		
		[301] = "BGM101_INTRO_CASE_1",
		"BGM102_TBD",
		"BGM103_TBD",
		"BGM104_INTRO_CASE_5",
		"BGM105_TBD",
		"BGM106_TBD",
		"BGM107_LUKE_ATMEYS_THEME",
		"BGM108_TBD",
		"BGM109_TBD",
		"BGM110_TBD",
		"BGM111_TBD",
		"BGM112_HAZAKURA_SHRINE",
		"BGM113_DAHLIAS_THEME",
		"BGM114_TBD",
		"BGM115_GODOTS_THEME",
		"BGM116_TBD",
		"BGM117_TBD",
		"BGM118_TBD",
		"BGM119_TBD",
		"BGM120_TBD",
		"BGM121_TBD",
		"BGM122_TBD",
		"BGM123_CORNERED_3",
		"BGM124_CORNERED_3_VARIATION",
		"BGM125_TBD",
		"BGM126_TBD",
		0,
		"BGM128_TBD",
		"BGM129_TBD",
		"BGM130_TBD",
		"BGM131_TBD",
		"BGM132_TBD",
		"BGM133_TBD",
		"BGM134_TBD",
		"BGM135_TBD",
		"BGM136_TBD",
		"BGM137_TBD",
		"BGM138_TBD",
		"BGM139_TBD",
		0,
		0,
		"BGM142_CORNERED_1_VERSION_3",
		"BGM143_CORNERED_1_VERSION_3_VARIATION",
		
		[350] = "SE090_JINGLE_SURPRISE_1",
		"SE091_JINGLE_SURPRISE_2",
		"SE092_JINGLE_SURPRISE_3",
		"SE093_JINGLE_SURPRISE_4",
		"SE094_JINGLE_SURPRISE_5",
		"SE095_SECURITY_ALARM",
		"SE096_ALARM_TURN_OFF",
		"SE097_UNKNOWN_CONFIRM",
		"SE098_UNKNOWN_SNAP",
		0,
		"SE09A_ELEVATOR_MOVING",
		"SE09B_ELEVATOR_ARRIVE",
		"SE09C_URN_BREAKING",
		"SE09D_UNKNOWN",
		"SE09E_UNKNOWN_CONFIRM_2",
		"SE09F_UNKNOWN_UNLOCK",
		"SE0A0_LIGHTNING",
		"SE0A1_VOICE_EDGEWORTH_HOLD_IT_FR",
		"SE0A2_VOICE_EDGEWORTH_TAKE_THAT_FR",
		"SE0A3_VOICE_MIA_OBJECTION_FR",
		"SE0A4_VOICE_MIA_HOLD_IT_FR",
		"SE0A5_VOICE_MIA_TAKE_THAT_FR",
		"SE0A6_VOICE_GODOT_OBJECTION_FR",
		"SE0A7_UNKNOWN_HIT",
		0,
		0,
		"SE0AA_UNKNOWN_CRITICAL_HIT",
		"SE0AB_JINGLE_SURPRISE_6",
		
		[382] = "SE0B0_UNKNOWN_SIZZLE_LONG",
		"SE0B1_UNKNOWN_SIZZLE_MID",
		"SE0B2_UNKNOWN_SIZZLE_SHORT",
		"SE0B3_UNKNOWN_SIZZLE_VERY_LONG",
		"SE0B4_UNKNOWN_BLEEP",
		"SE0B5_UNKNOWN_ENGINE",
		"SE0B6_UNKNOWN_IMPACT",
		"SE0B7_UNKNOWN",
		"SE0B8_UNKNOWN",
		0,
		0,
		"SE0BB_PHONE_RINGTONE_GODOT",
		"SE0BC_HAZAKURA_BELL",
		"SE0BD_UNKNOWN_WATER",
		"SE0BE_UNKNOWN_SPLASH",
		"SE0BF_VOICE_PHOENIX_EPIC_OBJECTION_JP",
		"SE0C0_EPIC_OBJECTION",
		"SE0C1_GHOST_SCREAM",
		"SE0C2_GHOST_EXORCISM",
		"SE0C3_UNKNOWN",
		"SE0C4_UNKNOWN",
		"SE0C5_EXCLAMATION_3",
		"SE0C6_GHOST_SCREAM_2",
		0,
		"SE0C8_COURTROOM_AUDIENCE",
		
		[500] = "SE0D0_VOICE_PHOENIX_OBJECTION_DE",
		"SE0D1_VOICE_PHOENIX_HOLD_IT_DE",
		"SE0D2_VOICE_PAYNE_OBJECTION_DE",
		"SE0D3_VOICE_EDGEWORTH_OBJECTION_DE",
		0,
		"SE0D5_VOICE_PHOENIX_TAKE_THAT_DE",
		"SE0D6_VOICE_FRANZISKA_OBJECTION_DE",
		// anything past here is from a different sequence bank that none of the usual tools handle
		// and is therefore pure guesswork
		0,
		0,
		0,
		// this assumes that WAVE SE ST01 is the first bank
		// and that the sequences appear in order of the wave files
		"SE0DA_VOICE_GODOT_OBJECTION_DE",
		"SE0DB_VOICE_EDGEWORTH_TAKE_THAT_DE",
		"SE0DC_VOICE_EDGEWORTH_HOLD_IT_DE",
		"SE0DD_VOICE_MIA_OBJECTION_DE",
		"SE0DE_VOICE_MIA_TAKE_THAT_DE",
		"SE0DF_VOICE_MIA_HOLD_IT_DE",
	},
	{
		/* apollo to be done */
		0
	}
};

/* 1024 is a placeholder, change when all things are known */
char *locations[4][256] = {
	{
		/* phoenix 1 */
		"LOCATION_FEY_PARTNER",
		"LOCATION_OFFICE",
		"LOCATION_DETENTION_CENTER",
		"LOCATION_OFFICE_GROSSBERG",
		"LOCATION_BLUECORP",
		"LOCATION_HOTEL_GATEWATER",
		"LOCATION_WRIGHT_PARTNER",
		"LOCATION_STUDIO_ENTRANCE",
		"LOCATION_STAFF_AREA",
		"LOCATION_CHANGING_ROOM",
		"LOCATION_STUDIO1_OUTSIDE",
		"LOCATION_STUDIO1_INSIDE",
		"LOCATION_STUDIO2_OUTSIDE",
		"LOCATION_TRAILER",
		"LOCATION_CRIMINAL_AFFAIRS",
		"LOCATION_ARCHIVE",
		"LOCATION_GOURD_LAKE",
		"LOCATION_BEACH_GOURD_LAKE",
		"LOCATION_FOREST_GOURD_LAKE",
		"LOCATION_BOAT_RENTAL",
		"LOCATION_HOUSE_OF_RENTAL",
		"LOCATION_BLANK",
		"LOCATION_PARKING_GARAGE",
		"LOCATION_OFFICE_EDGEWORTH", // CHANGEME
		"LOCATION_POLICE_STATION_ENTRANCE",
		"LOCATION_OFFICE_POLICE_CHEF",
		"LOCATION_SECURITY_ROOM",
		"LOCATION_EVIDENCE_ROOM",
		[255] = "LOCATION_NONE"
	},
	{
		/* phoenix 2 */
		
	},
	{
		/* phoenix 3 */
		
	},
	{
		/* apollo */
		
	}
};
